-- Migration 044 — SRD item seed + transactions backfill.
-- Spec-015 T035. Auto-generated by scripts/items-srd-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-srd-codegen.ts > supabase/migrations/044_srd_items_seed.sql
--
-- Idempotency:
--   * Phase 1: NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
--   * Phase 2: only sets item_node_id where it is NULL — re-running
--     never re-points a row that's already linked.

begin;

-- ─────────────────────────── Phase 1: seed ───────────────────────────

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot
    ) as (values
      ('longsword', 'Длинный меч', 'Универсальное холодное оружие. 1d8 (одной), 1d10 (двумя руками).', 'weapon', null, 15, 3, 'versatile'),
      ('shortsword', 'Короткий меч', 'Лёгкое финесное оружие. 1d6 колющий, есть свойство «фехтовальное».', 'weapon', null, 10, 2, '1-handed'),
      ('dagger', 'Кинжал', 'Лёгкое финесное оружие. 1d4. Можно метать на 20/60 футов.', 'weapon', null, 2, 1, '1-handed'),
      ('battleaxe', 'Боевой топор', 'Универсальный воинский топор. 1d8 (одной), 1d10 (двумя).', 'weapon', null, 10, 4, 'versatile'),
      ('greatsword', 'Большой меч', 'Двуручное тяжёлое оружие. 2d6 рубящий.', 'weapon', null, 50, 6, '2-handed'),
      ('maul', 'Двуручный молот', 'Двуручное тяжёлое оружие. 2d6 дробящий.', 'weapon', null, 10, 10, '2-handed'),
      ('halberd', 'Алебарда', 'Двуручное древковое оружие с дальностью досягаемости. 1d10 рубящий.', 'weapon', null, 20, 6, '2-handed'),
      ('longbow', 'Длинный лук', 'Двуручное дальнобойное оружие. 1d8 колющий, дальность 150/600 футов.', 'weapon', null, 50, 2, 'ranged'),
      ('shortbow', 'Короткий лук', 'Двуручное дальнобойное оружие. 1d6 колющий, дальность 80/320 футов.', 'weapon', null, 25, 2, 'ranged'),
      ('hand-crossbow', 'Ручной арбалет', 'Лёгкий дальнобойный арбалет. 1d6 колющий, дальность 30/120 футов.', 'weapon', null, 75, 3, '1-handed'),
      ('heavy-crossbow', 'Тяжёлый арбалет', 'Двуручный воинский арбалет. 1d10 колющий, дальность 100/400 футов.', 'weapon', null, 50, 18, '2-handed'),
      ('spear', 'Копьё', 'Универсальное оружие, можно метать. 1d6 (одной), 1d8 (двумя). Дальность 20/60.', 'weapon', null, 1, 3, 'versatile'),
      ('mace', 'Булава', 'Простое одноручное оружие. 1d6 дробящий.', 'weapon', null, 5, 4, '1-handed'),
      ('quarterstaff', 'Боевой посох', 'Простое универсальное оружие. 1d6 (одной), 1d8 (двумя).', 'weapon', null, 0.2, 4, 'versatile'),
      ('sickle', 'Серп', 'Простое лёгкое оружие. 1d4 рубящий.', 'weapon', null, 1, 2, '1-handed'),
      ('leather-armor', 'Кожаный доспех', 'Лёгкий доспех. AC 11 + Лвк, без помех скрытности.', 'armor', null, 10, 10, 'body'),
      ('studded-leather', 'Клёпаный кожаный доспех', 'Лёгкий доспех. AC 12 + Лвк, без помех скрытности.', 'armor', null, 45, 13, 'body'),
      ('chain-shirt', 'Кольчужная рубаха', 'Средний доспех. AC 13 + Лвк (макс +2).', 'armor', null, 50, 20, 'body'),
      ('scale-mail', 'Чешуйчатый доспех', 'Средний доспех. AC 14 + Лвк (макс +2). Помехи на скрытность.', 'armor', null, 50, 45, 'body'),
      ('half-plate', 'Полулаты', 'Средний доспех. AC 15 + Лвк (макс +2). Помехи на скрытность.', 'armor', null, 750, 40, 'body'),
      ('chain-mail', 'Кольчуга', 'Тяжёлый доспех. AC 16. Сила 13, помехи на скрытность.', 'armor', null, 75, 55, 'body'),
      ('plate-armor', 'Латный доспех', 'Тяжёлый доспех. AC 18. Сила 15, помехи на скрытность.', 'armor', null, 1500, 65, 'body'),
      ('shield', 'Щит', '+2 к AC. Занимает руку.', 'armor', null, 10, 6, 'shield'),
      ('rope-hempen-50ft', 'Верёвка пеньковая, 50 футов', 'Прочная верёвка длиной 50 футов.', 'misc', null, 1, 10, null),
      ('torch', 'Факел', 'Освещает 20 футов ярким светом, ещё 20 — тусклым. Горит 1 час.', 'misc', null, 0.01, 1, null),
      ('backpack', 'Рюкзак', 'Походный рюкзак, вмещает до 1 куб. фута / 30 фунтов.', 'misc', null, 2, 5, null),
      ('bedroll', 'Спальный мешок', 'Свёрнутый матрас и одеяло для сна на природе.', 'misc', null, 1, 7, null),
      ('whetstone', 'Точило', 'Камень для затачивания клинков. Несколько применений.', 'misc', null, 0.01, 1, null),
      ('lantern-hooded', 'Закрытый фонарь', 'Освещает 30 футов ярким светом и ещё 30 — тусклым. Расход масла: 1 час за пинту.', 'misc', null, 5, 2, null),
      ('oil-flask', 'Масло, бутыль', 'Бутылка лампового масла. Можно поджечь как метательную при попадании.', 'misc', null, 0.1, 1, null),
      ('tent-two-person', 'Двухместная палатка', 'Палатка, рассчитанная на двух персонажей.', 'misc', null, 2, 20, null),
      ('mirror-steel', 'Стальное зеркало', 'Полированное зеркало из стали.', 'misc', null, 5, 0.5, null),
      ('mess-kit', 'Походный набор посуды', 'Чашка, миска, ложка и складной чайник.', 'misc', null, 0.2, 1, null),
      ('thieves-tools', 'Воровские инструменты', 'Набор отмычек, шилов и зеркальца. Для проверки навыка взлома.', 'tool', null, 25, 1, null),
      ('healers-kit', 'Набор лекаря', '10 зарядов. Стабилизация умирающего без проверки.', 'tool', null, 5, 3, null),
      ('potion-of-healing', 'Зелье лечения', 'Восстанавливает 2d4+2 HP при выпивании.', 'consumable', 'common', 50, 0.5, null),
      ('potion-of-greater-healing', 'Зелье среднего лечения', 'Восстанавливает 4d4+4 HP.', 'consumable', 'uncommon', 200, 0.5, null),
      ('potion-of-superior-healing', 'Зелье отличного лечения', 'Восстанавливает 8d4+8 HP.', 'consumable', 'rare', 500, 0.5, null),
      ('antitoxin-vial', 'Антитоксин', 'Бутылка. Преимущество к спасброскам от яда на 1 час.', 'consumable', null, 50, 0, null),
      ('holy-water-flask', 'Святая вода', 'Метательная бутыль. 2d6 урона излучением нежити или исчадиям.', 'consumable', null, 25, 1, null),
      ('alchemists-fire', 'Алхимический огонь', 'Метательная бутыль. 1d4 огня в начале хода цели, пока он не потушит огонь.', 'consumable', null, 50, 1, null),
      ('acid-vial', 'Кислота, бутыль', 'Метательная бутыль. 2d6 кислотой при попадании.', 'consumable', null, 25, 1, null),
      ('poison-basic-vial', 'Простой яд', 'Покрывает одно оружие. При попадании цель проходит спасбросок Тел DC 10 или получает 1d4 яда.', 'consumable', null, 100, 0, null),
      ('longsword-plus-1', '+1 длинный меч', '+1 к броску атаки и урона. 1d8 / 1d10 рубящий.', 'magic-item', 'uncommon', 1000, 3, 'versatile'),
      ('cloak-of-protection', 'Плащ защиты', '+1 к AC и спасброскам, пока носите. Требует настройки.', 'wondrous', 'uncommon', 4000, 1, 'cloak'),
      ('boots-of-elvenkind', 'Сапоги эльфов', 'Шаги бесшумны. Преимущество на скрытность бесшумных движений.', 'wondrous', 'uncommon', 4000, 1, 'boots'),
      ('bag-of-holding', 'Сумка хранения', 'Внутреннее пространство 64 куб. фута / 500 фунтов; снаружи весит 15 фунтов.', 'wondrous', 'uncommon', 4000, 15, null),
      ('ring-of-protection', 'Кольцо защиты', '+1 к AC и спасброскам. Требует настройки.', 'magic-item', 'rare', 8000, 0, 'ring'),
      ('amulet-of-health', 'Амулет здоровья', 'Телосложение становится 19. Требует настройки.', 'magic-item', 'rare', 8000, 1, 'amulet'),
      ('gauntlets-of-ogre-power', 'Перчатки силы огра', 'Сила становится 19. Требует настройки.', 'magic-item', 'uncommon', 4000, 2, 'gloves')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, 'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new SRD items',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- ─────────────────────────── Phase 2: backfill ───────────────────────────

do $$
declare
  c_rec record;
  bf_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    update transactions tx
    set item_node_id = n.id
    from nodes n
    inner join item_attributes ia on ia.node_id = n.id
    where tx.campaign_id = c_rec.id
      and tx.kind = 'item'
      and tx.item_node_id is null
      and n.campaign_id = c_rec.id
      and ia.source_slug = 'srd-5e'
      and (
        lower(trim(tx.item_name)) = lower(trim(n.title))
        or lower(trim(coalesce(tx.item_name, ''))) = lower(coalesce(n.fields->>'srd_slug', ''))
      );

    get diagnostics bf_count = row_count;
    raise notice 'Campaign % (%): backfilled % transactions',
      c_rec.slug, c_rec.id, bf_count;
  end loop;
end $$;

commit;

-- Post-deploy verification (run manually if desired):
--
--   -- (a) seeded item count per campaign (expect 50 for fresh seeding)
--   select c.slug, count(n.id)
--     from campaigns c
--     left join nodes n on n.campaign_id = c.id
--                       and n.fields->>'srd_slug' is not null
--     group by c.slug order by c.slug;
--
--   -- (b) backfilled transactions per campaign
--   select c.slug, count(tx.id)
--     from campaigns c
--     left join transactions tx on tx.campaign_id = c.id
--                               and tx.item_node_id is not null
--                               and tx.kind = 'item'
--     group by c.slug order by c.slug;
--
--   -- (c) sanity: kind/link CHECK still satisfied
--   select count(*) from transactions
--     where (kind <> 'item' and item_node_id is not null);
