-- Migration 060 — dnd.su items seed: Candlekeep Mysteries.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('alchemy-jug-blue', 'Алхимический сосуд (синий)', 'Этот керамический кувшин, кажется способным вместить 1 галлон жидкости и весит 12 фунтов вне зависимости от того, полный он или пустой. Если его потрясти, то можно услышать звуки плескающийся жидкости, даже если кувшин пуст.

Вы можете действием назвать одну жидкость из приведённой ниже таблицы, отчего кувшин начнёт её производить. После этого вы можете ещё одним действием откупорить кувшин и вылить эту жидкость из сосуда со скоростью до 2 галлонов в минуту. Максимальное количество жидкости, которое может произвести кувшин, зависит от вида жидкости, названной вами.

После того, как кувшин начинает производить выбранную жидкость, он не может производить другую, или произвести названную жидкость в объёме больше её максимума, пока не наступит следующий рассвет.

Жидкость | Макс. объем
---|---
Вино | 1 галлон
Вода, пресная | 8 галлонов
Вода, солёная | 12 галлонов
Горячий заваренный чай | 1 кварта
Майонез | 2 галлона
Масло | 1 кварта
Мёд | 1 галлон
Пиво | 4 галлона
Уксус | 2 галлона', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/2113-alchemy-jug-blue/', 'Candlekeep Mysteries'),
      ('alchemy-jug-orange', 'Алхимический сосуд (оранжевый)', 'Этот керамический кувшин, кажется способным вместить 1 галлон жидкости и весит 12 фунтов вне зависимости от того, полный он или пустой. Если его потрясти, то можно услышать звуки плескающийся жидкости, даже если кувшин пуст.

Вы можете действием назвать одну жидкость из приведённой ниже таблицы, отчего кувшин начнёт её производить. После этого вы можете ещё одним действием откупорить кувшин и вылить эту жидкость из сосуда со скоростью до 2 галлонов в минуту. Максимальное количество жидкости, которое может произвести кувшин, зависит от вида жидкости, названной вами.

После того, как кувшин начинает производить выбранную жидкость, он не может производить другую, или произвести названную жидкость в объёме больше её максимума, пока не наступит следующий рассвет.

Жидкость | Макс. объем
---|---
Вино | 1 галлон
Вода, пресная | 8 галлонов
Вода, солёная | 12 галлонов
Майонез | 2 галлона
Масло | 1 кварта
Мёд | 1 галлон
Пиво | 4 галлона
Соевый соус | 1 галлон
Уксус | 2 галлона', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/2112-alchemy-jug-orange/', 'Candlekeep Mysteries'),
      ('cracked-driftglobe', 'Треснувшая парящая сфера', 'Эта небольшая сфера из толстого стекла весит 1 фунт. Находясь в пределах 60 футов от неё вы можете произнести командное слово и заставить сферу излучать свет, как если бы на неё было наложено заклинание [_свет [light]_](/spells/307-light/).', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/2118-cracked-driftglobe/', 'Candlekeep Mysteries'),
      ('gloves-of-soul-catching', 'Перчатки ловли душ', 'Пока вы носите эти перчатки, ваше значение Телосложения равно 20. Это свойство перчаток не работает, если ваше Телосложение уже 20 или больше.

После того, как вы попали своей безоружной атакой, будучи в этих перчатках, вы можете использовать их, чтобы нанести цели дополнительно 2к10 урона силовым полем и восстановить количество хитов, равное нанесённому урону силовым полем. В качестве альтернативы вместо того, чтобы восстановить хиты таким образом, вы можете получить преимущество на один бросок атаки, проверку характеристики или спасбросок, который вы совершите до конца вашего следующего хода.', 'wondrous', 'legendary', null, null, null, true, 'https://dnd.su/items/2120-gloves-of-soul-catching/', 'Candlekeep Mysteries'),
      ('nether-scroll-of-azumar', 'Нетерильский свиток Азумара', 'В отличие от большинства свитков, Нетерильский свиток Азумара не является расходуемым магическим предметом. Требуется 30 дней сосредоточенного изучения (по крайней мере 8 часов в день), чтобы попытаться понять этот свиток. После завершения этого изучения вы должны совершить проверку Интеллекта (Магия) Сл 25. Если эта проверка проваливается, то вы получаете 16к10 урона психической энергией, и вы можете повторить данную проверку спустя 30 дней сосредоточенного изучения.

Когда вы преуспеваете в проверке, вы получите следующие преимущества:

Ваше значение Интеллекта увеличивается на 2, максимум увеличивается до 22. Как только вы получите это преимущество, вы не можете использовать этот свиток ещё раз, чтобы увеличить своё значение Интеллекта.
Вы совершаете с преимуществом спасброски от заклинаний и прочих магических эффектов.
Когда вы получаете преимущества свитка, [каменный голем [stone golem]](/bestiary/186-stone_golem/) магическим образом появляется в свободном пространстве в пределах 60 футов от вас и действует как ваш союзник. Если вы умираете, то голем обращается в пыль.', 'consumable', 'legendary', null, null, null, false, 'https://dnd.su/items/2114-nether-scroll-of-azumar/', 'Candlekeep Mysteries'),
      ('serpent-scale-armor', 'Доспех из змеиной чешуи', 'Этот магический доспех сделан из переливающейся чешуи. Пока вы в него облачены, вы можете использовать свой обычный модификатор Ловкости (вместо максимального значения +2) при определении КД. Кроме того, этот доспех не накладывает помеху на ваши проверки Ловкости (Скрытность).', 'armor', 'uncommon', null, null, 'body', false, 'https://dnd.su/items/2119-serpent-scale-armor/', 'Candlekeep Mysteries'),
      ('serpents-fang', 'Змеиный клык', 'Этот магический меч с одной режущей кромкой сделан из заточенного клыка гигантской змеи. Его рукоять меняет форму, чтобы приспособиться к хвату любого существа, которое использует его. Оружие наносит дополнительно 1к10 урона ядом любой цели, по которой попадёт.', 'weapon', 'rare', null, null, '1-handed', false, 'https://dnd.su/items/2117-serpents-fang/', 'Candlekeep Mysteries'),
      ('staff-of-fate', 'Посох судьбы', 'Этот хрустальный прозрачный посох можно использовать как магический боевой посох, предоставляющий бонус +3 к броскам атаки и урона им.

**_Изменение результата._** Посох имеет 6 зарядов. Бонусным действием вы можете потратить 1 заряд посоха, чтобы дать себе или одному другому существу, которое вы можете увидеть, к4. Получатель может бросить этот к4 и добавить результат броска к одной проверке характеристики, броску атаки, броску урона или спасброску, который он совершает до начала вашего следующего хода. Если этот дополнительный куб не будет использован до этого момента, то он исчезает.

Если вы истратили последний заряд, бросьте к20. При результате «9» или ниже посох становится немагическим боевым посохом, который ломается при первом попадании и нанесении урона. При результате «10» или выше посох восстанавливает 1к6 своих израсходованных зарядов.', 'magic-item', 'very-rare', null, null, null, true, 'https://dnd.su/items/2116-staff-of-fate/', 'Candlekeep Mysteries'),
      ('watchful-helm', 'Шлем бдительности', 'Пока вы носите этот шлем, вы получаете бонус +1 к КД и остаетесь в курсе своего окружения даже во сне, и продолжаете воспринимать окружающую обстановку даже во сне, и вы получаете преимущество на проверки Мудрости (Восприятие), полагающиеся на зрение.

Бонусным действием вы можете наложить с помощью этого шлема заклинание _[видение невидимого [see invisibility]](/spells/20-see_invisibility/)_. Как только это свойство шлема будет использовано, его нельзя использовать снова до следующего рассвета.', 'wondrous', 'very-rare', null, null, null, true, 'https://dnd.su/items/2115-watchful-helm/', 'Candlekeep Mysteries')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Candlekeep Mysteries)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
