-- Migration 062 — dnd.su items seed: Curse of Strahd.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('blood-spear', 'Кровавое копьё', 'Каван был беспощадным вождём, чьё племя веками жило в Горах Балинок, задолго до прибытия Страда фон Заровича. Хотя он был весьма жив, Кавану были присущи некоторые черты, присущие вампирам: он спал днём и охотился ночью, он пил кровь своих жертв, и он жил под землёй. В бою он использовал копьё измазанное кровью. Это было первое кровавое копьё – оружие, что пило кровь тех, кого оно убивало, и передавало жизнь его носителю, наделяя его силами, чтобы сражаться дальше.

Когда вы попадаете рукопашной атакой этим магическим копьём и понижаете хиты цели до 0, вы получаете 2к6 временных хитов.

Любое существо может использовать это копьё, но лишь персонаж, избранный Каваном для этого, получает бонус +2 к броскам атаки и урону этим волшебным оружием.', 'weapon', 'uncommon', null, null, '1-handed', true, 'https://dnd.su/items/2201-blood-spear/', 'Curse of Strahd'),
      ('gulthias-staff', 'Посох Галтиас', 'Созданный из ветви древа Галтиас (см. раздел «[Заразы](/articles/21-zarazy/)» в _«Бестиарии»_), посох Галтиас – это пористый отрез чёрного дерева. Его зло заставляет зверей явно чувствовать себя некомфортно в пределах 30 футов от него. Посох имеет 10 зарядов и восполняет 1к6+4 потраченных зарядов на закате каждого дня.

Если посох будет сломан или сожжён до пепла, древесина испускает ужасающий, нечеловеческий крик, который слышно на 300 футов. Все**[**заразы****[blights]**](/articles/21-zarazy/),** которые услышат этот крик, немедленно чахнут и погибают.

**_Удар вампира._** Посох может быть использован как волшебный боевой посох. При попадании он наносит урон как обычный посох, а вы можете потратить 1 заряд, чтобы восполнить количество хитов, равное урону, нанесённому этим оружием. Каждый раз, когда тратится заряд, посох истекает кроваво-красной слизью и вы должны преуспеть в спасброске Мудрости Сл 12 или стать подверженным кратковременному безумию (см. «[Безумие](https://dnd.su/articles/mechanics/151-madness/)» в главе 8 _«Руководства Мастера»_).

**_Гибель для зараз._** Пока вы настроены на посох, [заразы [blights]](/articles/bestiary/21-zarazy/) и другие злые существа с типом «растение» не воспринимают вас враждебно, пока вы не причиняете им вреда.', 'magic-item', 'rare', null, null, null, true, 'https://dnd.su/items/2202-gulthias-staff/', 'Curse of Strahd'),
      ('icon-of-ravenloft', 'Символ Равенлофта', '_Символ Равенлофта_ — это 12-дюймовая статуэтка, выполненная из чистейшего серебра, весящая 10 фунтов. Она изображает жреца, молящегося на коленях.

Символ передал Страду архижрец Кирил Ромулич, старый друг семьи, чтобы освятить замок и его часовню.

Находящиеся в пределах 30 футов от символа существа находятся под действием эффекта заклинания [защита от зла и добра [protection from evil and good]](/spells/99-protection_from_evil_and_good/), действующего против Нежити и Исчадий. Лишь существо, настроенное на символ, может использовать прочие его свойства.

**_Гадание._** Вы можете действием при помощи символа сотворить заклинание [гадание [augury]](/spells/40-augury/) без необходимости использовать материальные компоненты. Использовав это свойство, его более нельзя использовать до следующего рассвета.

**_Погибель для нежити._** Вы можете использовать символ как святой символ при использовании умения «Изгнание нежити» или «Изгнание нечисти. При этом повысьте Сл спасброска на 2.

**_Лечение ран._** Держа символ, вы можете действием излечить одно существо, которое видите в пределах 30 футов. Цель восполняет 3к8 + 3 хита, если оно не Нежить, Конструкт или Исчадие. Использовав это свойство, его более нельзя использовать до следующего рассвета.', 'wondrous', 'legendary', null, null, null, true, 'https://dnd.su/items/2204-icon-of-ravenloft/', 'Curse of Strahd'),
      ('saint-markovias-thighbone', 'Бедренная кость святой Марковии', '_Бедренная кость святой Марковии_ обладает свойствами [булавы распада [mace of disruption]](/items/8-mace_of_disruption/). Если ею будут нанесёны один или несколько ударов по [вампиру [vampire]](/bestiary/307-vampire/) или [порождению вампира [vampire spawn]](/bestiary/308-vampire_spawn/) во время одной битвы, бедренная кость рассыпается в прах, как только битва подходит к концу.

В юности Марковия, последовав зову сердца, стала священницей Утреннего бога вскоре после своего восемнадцатилетия. Она показала себя харизматичной проповедницей и к тридцати годам обладала репутацией той, перед которой не устоять никакому злу.

Марковия долгое время считала Страда безумным тираном, но лишь после его обращения в вампира решилась выступить против него. Когда она уже собрала своих последователей и приготовилась выступить в поход на замок Равенлофт, Страд отправил группу порождений вампира к ней в аббатство. Они выступили против Марковии и были уничтожены все до единого.

Праведная победа зажгла её уверенность, и Марковия направилась в замок Равенлофт. Великая битва бушевала от катакомб до парапетов. В итоге Марковия так и не вернулась в Баровию, а Страд долгое время хромал, скалясь от боли. Говорят, что он запер Марковию в крипте под замком, и её останки лежат там и по сей день.

Хотя её тело истлело, частичка святости Марковии перешла в её кости. Уцелевшая бедренная кость наделена силой наносить Нежити ужасающие ранения.', 'weapon', 'rare', null, null, '1-handed', true, 'https://dnd.su/items/2205-saint-markovias-thighbone/', 'Curse of Strahd'),
      ('sunsword', 'Солнечный меч', '_Солнечный меч_ – это уникальный клинок, когда-то принадлежавший брату Страда, Сергею фон Заровичу. В своей изначальной форме он имел платиновую рукоять и гарду, а тонкий кристальный клинок был столь же крепок, как и сталь.

Страд нанял могущественного волшебника по имени Хазан, чтобы тот уничтожил оружие после смерти Сергея. Первая часть процесса требовала, чтобы клинок покинул рукоять, и в этом Хазан преуспел. Пока Хазан был занят уничтожением клинка, его ученик украл рукоять и сбежал. Хазан позже обнаружил покалеченный труп своего ученика в Сваличском Лесу, но рукоять так и не была найдена. Чтобы избежать гнева вампира, Хазан сказал Страду, что оружие было уничтожено полностью.

Рукоять, обладавшая собственным сознанием, знает, что ей никогда не воссоединиться с изначальным клинком. Впрочем, она обладает, всеми свойствами [солнечного клинка [sun blade]](/items/217-sun_blade/).

**_Сознание._**_Солнечный меч_ – это разумное хаотично-доброе оружие с Интеллектом 11, Мудростью 17 и Харизмой 16. Он обладает обычным слухом и зрением в радиусе 60 футов. Оружие общается по средству передачи эмоций существу, носящему его.

**_Личность._** Главная цель _солнечного меча_ – это уничтожение Страда, не столько из-за того, что он хочет освободить земли Баровии от зла, но потому, что он жаждет мести за потерю кристального клинка. Оружие втайне страшится собственного уничтожения.', 'weapon', 'legendary', null, null, '1-handed', true, 'https://dnd.su/items/2206-sunsword/', 'Curse of Strahd')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Curse of Strahd)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
