-- Migration 063 — dnd.su items seed: Descent into the Lost Caverns of Tsojcanth.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('demon-skin', 'Шкура демона', 'Этот доспех похож на котел с пузырящимся чёрным ихором. Когда вы настраиваетесь на него, котел исчезает, а ихор прилипает к вашей коже. Доспех можно носить под одеждой, он не сковывает ваши движения, а также не мешает вашему телу. После надевания доспеха его будет невозможно снять, пока вы добровольно не захотите это сделать или не умрете. В таком случае котел вновь появится, а ихор перетечет в него.

Пока вы носите этот доспех, вы получаете сопротивление урону ядом. Также он не накладывает помеху на проверки Ловкости (Скрытность).', 'armor', 'rare', null, null, 'body', true, 'https://dnd.su/items/8726-demon-skin/', 'Descent into the Lost Caverns of Tsojcanth'),
      ('iggwilvs-horn', 'Рог Иггвилв', 'Действием вы можете подуть в рог и наложить одно из следующих заклинаний: [руки Хадара [arms of Hadar]](/spells/305-arms_of_hadar/), [туманное облако [fog cloud]](/spells/351-fog_cloud/), [порыв ветра [gust of wind]](/spells/255-gust_of_wind/), [паутина [web]](/spells/227-web/) (Сл спасброска 13).

После того, как рог был использован для наложения заклинания, его нельзя использовать для наложения этого же заклинания до следующего рассвета.', 'wondrous', 'rare', null, null, null, true, 'https://dnd.su/items/8727-iggwilvs-horn/', 'Descent into the Lost Caverns of Tsojcanth'),
      ('potion-of-polychromy', 'Зелье многоцветности', 'Выпив это зелье, вы и всё, что вы несёте и носите, приобретёт изменчивый оттенок всевозможных цветов на 1 час. В течение это времени вы можете бонусным действием поменять палитру цветов на любую на ваш выбор. Если вы мимикрируете под оттенки окружающей среды, то они постоянно меняются в соответствии с обстановкой, и вы совершаете проверки Ловкости (Скрытность) с преимуществом, пока не измените цвет или эффект зелья не перестанет действовать.

Зелье расслаивается на семь ярких полос несмешивающихся жидкостей и напоминает на вкус сироп.', 'consumable', 'uncommon', null, null, null, false, 'https://dnd.su/items/8728-potion-of-polychromy/', 'Descent into the Lost Caverns of Tsojcanth'),
      ('tashas-creeping-keelboat', 'Лодка на гусиных ножках Таши', 'Это средство передвижения является лодкой шириной в 10 футов и длиной в 30 футов. У нее есть четыре гусиных лапки, которые позволяют ей передвигаться как по суше, так и по воде. Скорость ходьбы и плавания составляет 20 футов, но она не может передвигаться под водой. Лодка движется в соответствии с отданными вами командами, а существа по вашему выбору получают бонус +1 к КД, пока находятся внутри.

Лодка может беспрепятственно перевозить до 1 000 фунтов. Она способна выдержать вес вдвое больше, но при этом будет двигаться с половинной скоростью, если перевозит больше своей нормы.', 'wondrous', 'very-rare', null, null, null, true, 'https://dnd.su/items/8729-tashas-creeping-keelboat/', 'Descent into the Lost Caverns of Tsojcanth')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Descent into the Lost Caverns of Tsojcanth)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
