-- Migration 064 — dnd.su items seed: Dragonlance: Shadow of the Dragon Queen.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('flying-citadel-helm', 'Руль летающей крепости', 'Задача этого богато украшенного сидения заключается в том, чтобы управлять перемещением летающей крепости, в которой оно установлено. У сидения КД 15, 18 хитов и иммунитет к урону ядом и психической энергии. Оно разрушается, если его хиты уменьшаются до 0.

Ощущение настройки на _руль летающей крепости_ похоже на покалывание, которые вы испытываете, когда затекает рука или нога, но менее интенсивное. Пока вы настроены на _руль летающей крепости_ и сидите на нём, вы получаете следующие преимущества, пока поддерживаете концентрацию (как при концентрации на заклинании):

Вы можете использовать _руль летающей крепости_ для её перемещения по воздуху на расстояние вплоть до 80 футов/раунд или 8 миль/час.
Вы можете поворачивать цитадель, хоть и несколько неуклюже. Это похоже на то, как для маневрирования морским кораблём можно использовать обычный штурвал или вёсла.
В любое время вы можете видеть и слышать, что происходит с самой высокой точки вне крепости, словно вы находитесь в этом месте.

Если ни одно существо не поддерживает концентрацию на руле, крепость неподвижно висит в воздухе.

**_Передача настройки._** Действием или бонусным действием вы можете коснуться согласного заклинателя, после чего это существо немедленно настраивается на руль летающей крепости, а ваша настройка заканчивается.

**_Крушение._** Если _руль летающей крепости_ будет уничтожен, крепость, в которой он установлен, теряет энергию и начинает разрушаться. Если разрушающаяся крепость находится в воздухе, она снижается на 30 футов за раунд или 300 футов в минуту. Все существа в крепости или на земле в пределах 120 футов от крепости в месте приземления должны совершить спасбросок Ловкости Сл 20, получая 39 (6к12) дробящего урона при провале или половину этого урона при успехе.', 'wondrous', 'very-rare', null, null, null, true, 'https://dnd.su/items/5486-flying-citadel-helm/', 'Dragonlance: Shadow of the Dragon Queen'),
      ('kagonesti-forest-shroud', 'Лесной покров кагонести', 'Похоже, этот плащ сделан из сплетённых вместе осенних листьев. Пока вы носите этот плащ, вы с преимуществом совершаете проверки Ловкости (Скрытность) и бонусным действием можете магическим образом телепортироваться вместе со всем несомым и носимым снаряжением в незанятое пространство, которые вы можете видеть в пределах 30 футов. После этого вы с преимуществом совершаете следующий бросок атаки до конца хода. Вы не можете повторно использовать это бонусное действие до следующего рассвета.', 'wondrous', 'rare', null, null, null, true, 'https://dnd.su/items/5487-kagonesti-forest-shroud/', 'Dragonlance: Shadow of the Dragon Queen'),
      ('mirror-of-reflected-pasts', 'Зеркало отражённого прошлого', 'Это зеркало эльфийской работы показывает смотрящему в него позитивные воспоминания. У зеркала высотой 3 фута и весом 25 фунтов КД 11, 10 хитов и уязвимость к дробящему урону. Оно разбивается вдребезги и разрушается, если его хиты уменьшаются до 0.

Удерживая зеркало вертикально, действием вы можете произнести командное слово и активировать его. Активированное зеркало парит в воздухе и может быть уничтожено, но не перемещено. Оно остаётся активированным до тех пор, пока действием вы снова не произнесёте командное слово или не закончится ваша настройка на зеркало, и тогда зеркало без вреда опустится на землю. После деактивации вы не можете повторно активировать зеркало до следующего рассвета.

Если другое существо, не являющееся Конструктом, увидит своё отражение в активированном зеркале в пределах 30 футов от него, оно должно преуспеть в спасброске Мудрости Сл 15, иначе станет парализованным, пока зеркало не будет деактивировано или пока это существо больше не сможет видеть зеркало. Существо, парализованное зеркалом, может повторять спасбросок в конце каждого своего хода, оканчивая эффект при успехе. Если цель успешно совершила спасбросок или действие эффекта закончилось, она получает иммунитет к эффекту зеркала на следующие 24 часа.

Парализованное существо видит события из своего прошлого, отражённое в зеркале. Эти воспоминания не реальные, а скорее идеализированные версии тех событий. Наблюдатели, находящиеся поблизости, могут увидеть вспышки этих воспоминаний, если не будут напрямую смотреть в зеркало.', 'wondrous', 'very-rare', null, null, null, true, 'https://dnd.su/items/5488-mirror-of-reflected-pasts/', 'Dragonlance: Shadow of the Dragon Queen')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Dragonlance: Shadow of the Dragon Queen)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
