-- Migration 071 — dnd.su items seed: Ghosts of Saltmarsh.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('charm-of-plant-command', 'Амулет командования растениями', 'Этот амулет размером с кулак сделан из пучка сухих стеблей растений, обернутых серебряной нитью. Подвешенный на кожаном ремешке, он обычно носится на шее или прикрепляется к поясу.

Амулет имеет 3 заряда. Пока вы носите амулет, вы можете действием потратить 1 заряд, чтобы наложить заклинание [разговор с растениям [speak with plants]](/spells/294-speak_with_plants/). Пока заклинание действует, вы также получаете преимущество на проверки Харизмы, чтобы влиять на поведение, манеры и отношение растений. Амулет восстанавливает все израсходованные заряды на рассвете каждого дня.', 'wondrous', 'rare', null, null, null, true, 'https://dnd.su/items/2370-charm-of-plant-command/', 'Ghosts of Saltmarsh'),
      ('cursed-luckstone', 'Проклятый камень удачи', 'Этот плоский, серо-чёрный речной камень исписан неизвестными магическими символами и на ощупь кажется прохладным. Во время ношения камня вы можете получить преимущество на одну проверку характеристик по вашему выбору. Камень нельзя использовать подобным образом до следующего рассвета.

**_Проклятие._** Этот предмет проклят. Настроившись на него, вы тоже становитесь проклятым, пока на вас не используют заклинание [снятие проклятья [remove curse]](/spells/326-remove_curse/) или подобную магию. Пока вы остаетесь проклятым, вы не можете выбросить камень, так как он немедленно телепортируется обратно в ваш карман или рюкзак. После того, как вы используете свойство камня, ваши следующие две проверки характеристик совершаются с помехой.', 'wondrous', 'uncommon', null, null, null, true, 'https://dnd.su/items/2368-cursed-luckstone/', 'Ghosts of Saltmarsh'),
      ('helm-of-underwater-action', 'Шлем подводных действий', 'Надев этот латунный шлем, вы можете дышать под водой, получаете тёмное зрение с дальностью 60 футов, и получаете скорость плавания 30 футов.', 'wondrous', 'uncommon', null, null, null, true, 'https://dnd.su/items/2369-helm-of-underwater-action/', 'Ghosts of Saltmarsh'),
      ('pipe-of-remembrance', 'Трубка воспоминаний', 'Эта длинная, тонкая деревянная трубка украшена чашей из гладкого речного камня. Когда трубка зажжена, дым, выдыхаемый из неё, не рассеивается, а задерживается вокруг курящего. Через 10 минут дым образует движущиеся фигуры, которые воспроизводят самые впечатляющие и героические достижения владельца в течение 5 минут. Когда это реалистичное представление заканчивается, дым рассеивается. Трубку нельзя использовать таким образом до следующего рассвета.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/2367-pipe-of-remembrance/', 'Ghosts of Saltmarsh'),
      ('pressure-capsule', 'Капсула давления', 'Эта маленькая капсула сделана из пчелиного воска, смешанного с песком и различными заколдованными водорослями. Существо, которое употребляет капсулу давления, игнорирует эффекты плавания на глубине более 100 футов (см. [плавание под водой](/articles/mechanics/158-movement_and_position/#underwater.swimming)).

У этого предмета нет прописанного времени действия. В качестве ориентиров можете использовать следующее:

ведущий дизайнер D&D 5e говорил, что в следующем издании книги время действия будет около 8 часов
адаптация приключения для Adventurers League устанавливает время действия капсулы в играх лиги в 1 час', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/2365-pressure-capsule/', 'Ghosts of Saltmarsh'),
      ('sekolahian-worshiping-statuette', 'Статуэтка для поклонения Секолаху', 'Искусно вырезанная из песчаника, эта статуэтка высотой в 1 фут изображает акулу, извивающуюся в воде с открытым ртом. Если какое-либо Крошечное морское животное находится в пределах 1 дюйма от рта статуэтки, акула оживает и наносит ей 1 колющий урон. Акула может наносить урон подобным образом не чаще одного раза в час.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/2366-sekolahian-worshiping-statuette/', 'Ghosts of Saltmarsh')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Ghosts of Saltmarsh)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
