-- Migration 073 — dnd.su items seed: Hoard of the Dragon Queen.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('black-dragon-mask', 'Маска черного дракона', 'Эта глянцевая эбонитовая маска выполнена в виде черепа с рогами. Маска меняет свою форму, чтобы подходить настроившемуся на неё носителю. Пока вы носите маску и настроены на неё, вам доступны следующие свойства.

**_Поглощение урона_**. У вас есть сопротивление урону от кислоты. Если у вас уже есть такое свойство, полученное от другого источника - вы получает иммунитет к урону от кислоты. Если у вас есть и иммунитет к кислоте, также полученный иным путём, то вы восполняете хиты, равные половине урона кислотой, нанесённого вам.

**_Драконье величество_**. Пока вы не носите доспехов, вы можете прибавлять бонус Харизмы к своему Классу Доспеха.

**_Драконье дыхание_**. Если вы обладаете _Оружием дыхания_ , которому требуется отдых для перезарядки, оно получает свойство "_Перезарядка 6"_.

**_Драконье зрение_**. Вы получаете тёмное зрение на 60 футов, или дополнительные 60 футов уже имеющейся такой способности. Раз в день, вы можете получить слепое зрение на расстоянии 30 футов на 5 минут.

**_Драконий язык_**. Вы говорите и понимаете Драконий. Вы также проходите проверки Харизмы по отношению к чёрным драконам с преимуществом.

**_Легенд_ _арное сопротивление (1/день)_**_._ Если вы проваливаете спасбросок, вы можете выбрать вместо этого преуспеть в нём.

**_Дыхание под водой_**. Вы можете дышать под водой.', 'wondrous', 'legendary', null, null, null, true, 'https://dnd.su/items/297-black-dragon-mask/', 'Hoard of the Dragon Queen'),
      ('hazirawn', 'Хазирун', 'Разумный (нейтрально-злой) двуручный меч, _Хазирун_ , способен говорить на Общем и Нетерезском языках. Даже если вы не настроены на меч, вы получаете бонус +1 к броскам атаки и урона, проводимыми этим оружием. Если вы не настроены на _Хазирун_ , вы наносите дополнительные 1к6 урона некротической энергией попадая этим оружием.

**_Повышенное усиление_.** Пока вы настроены на это оружие, его бонус к броскам атаки и урона увеличивается до +2 и попадание наносит дополнительные 2к6 урона некротической энергией (вместо 1к6).

**_Заклинания_**. _Хазирун_ имеет 4 заряда для накладывания заклинаний. Пока меч настроен на вас и вы держите его в руках, вы можете накладывать [обнаружение магии [detect magic]](/spells/195-detect_magic/) (1 заряд), [обнаружение зла и добра [detect evil and good]](/spells/194-detect_evil_and_good/) (1 заряд) или [обнаружение мыслей [detect thoughts]](/spells/196-detect_thoughts/) (2 заряда). Каждую полночь, _Хазирун_ восполняет 1к4 потраченных зарядов.

**_Ранящий_.** Пока вы настроены на это оружие, любое существо, по которому вы попали _Хазируном_ не может восполнять хиты в течение 1 минуты. Цель может проходить спасбросок Телосложения Сл 15 в конце каждого своего хода, при успехе завершая этот эффект раньше времени.', 'weapon', 'legendary', null, null, '2-handed', true, 'https://dnd.su/items/298-hazirawn/', 'Hoard of the Dragon Queen'),
      ('insignia-of-claws', 'Эмблема когтей', 'Самоцветы на эмблеме Культа Дракона загораются пурпурным, когда вы вступаете в схватку, усиливая ваши кулаки или природное оружие.

Пока вы носите эмблему, вы получаете +1 к броскам атаки и урона которые вы совершаете безоружными ударами или естественным оружием. Также такие атаки считаются магическими.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/299-insignia-of-claws/', 'Hoard of the Dragon Queen'),
      ('wand-of-winter', 'Волшебная палочка зимы', 'Волшебная палочка выглядит и на ощупь как сосулька.

У палочки есть 7 зарядов, которые можно использовать, чтобы творить заклинания с её помощью. С палочкой в руке, вы можете использовать ваше действие чтобы сотворить одно из следующих заклинаний, даже если вы не способны творить заклятия:

Никаких компонентов для этого не требуется.

Волшебная палочка восполняет 1к6+1 потраченных зарядов каждый день на рассвете. Если вы потратите последний заряд палочки, бросьте к20. При результате 20, палочка плавится у вас в руках - она разрушена навсегда.', 'magic-item', 'rare', null, null, null, true, 'https://dnd.su/items/300-wand-of-winter/', 'Hoard of the Dragon Queen')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Hoard of the Dragon Queen)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
