-- Migration 074 — dnd.su items seed: Honor among Thieves.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('helm-of-disjunction', 'Шлем разъединения', 'Волшебник Морденкайнен создал этот гладкий золотой шлем. Если он и создал более одного шлема разъединения, их ещё предстоит найти.

Нося этот шлем, действием вы можете испустить импульс антимагии, расходящийся в сферу радиусом 300 футов с центром на вас. Импульс обладает следующими эффектами:

**Разъединение магических предметов**. Зелья и свитки в области действия уничтожаются. Свойства всех остальных магических предметов в области действия подавляются на 1 минуту. Импульс не воздействует на магические предметы на вас, а также на артефакты.

**Разъединение заклинаний**. Все активные заклинания прекращаются, если существо, объект или место воздействия хотя бы частично находится в области действия.

**Силовая волна**. Импульс достаточно силён, чтобы сбить с ног существ рядом с вами. Каждое существо в пределах 30 футов от вас должно преуспеть в спасброске Силы Сл 15, иначе будет сбито с ног.

После использования этого свойства шлема оно не может быть использовано вновь в течение 1к4 дней.', 'wondrous', 'legendary', null, null, null, true, 'https://dnd.su/items/5506-helm-of-disjunction/', 'Honor among Thieves'),
      ('hither-thither-staff', 'Посох Туда-Сюда', 'В верхнюю часть этой трости инкрустирован сверкающий самоцвет. В посохе 4 заряда, и посох восстанавливает 1к4 зарядов на каждом рассвете.

Действием вы можете потратить заряд посоха и создать два связанных друг с другом портала телепортации. Каждый должен быть расположен на видимых вами плоских поверхностях по вашему выбору в пределах 1500 футов от вас. Или же вы можете действием потратить 1 заряд, чтобы переместить один или оба портала, соблюдая те же условия. Поверхность, на которой создаётся портал, должна быть достаточного размера, чтобы вместить его. Оба портала — двумерные, светящиеся овалы, образующие открытый проход до 6 футов высотой и 4 футов шириной. Любое существо или предмет, попадающее в один из порталов, выходит из второго, как если бы оба создавали проход между соответствующими точками.

Портал может быть создан на движущейся поверхности, но эффект завершается, как только порталы находятся более чем в 1 миле друг от друга. Держа посох, вы можете бонусным действием закрыть оба портала (завершая эффект) или подавить один из них, так что он исчезнет, пока вы не переместите его (см. выше): пока один из порталов подавлен, вторым нельзя воспользоваться. Иначе порталы действуют 24 часа.', 'magic-item', 'legendary', null, null, null, false, 'https://dnd.su/items/5505-hither-thither-staff/', 'Honor among Thieves'),
      ('horn-of-beckoning-death', 'Рог Манящей Смерти', 'Выглядящее как рог небольшого дракона, это магическое устройство начинает светиться изнутри адским светом, если взять его в руки. Держа этот рог, действием вы можете вызвать магию некромантии, известную как Манящая Смерть.

Манящая Смерть появляется в начале вашего следующего хода в виде сферического облака кроваво-красного дыма радиусом 30 футов с центром на роге. Сфера не передвигается вместе с рогом. В начале каждого вашего хода радиус сферы увеличивается на 30 футов. Облако исчезает через 10 минут или когда ваша [концентрация](https://dnd.su/articles/mechanics/157-spellcasting/#concentration) на поддержании эффекта завершается. Любое существо (включая вас) с 9 хитами или меньше, заканчивающее свой ход в облаке, убивается Манящей Смертью. Гуманоиды, убитые Манящей Смертью, немедленно обращаются в [зомби [zombie]](/bestiary/9-zombie/), повинующихся создателю рога, личу Сзассу Тэму.

После использования этого свойства оно не может быть вновь использовано в течение 1 года.', 'wondrous', 'legendary', null, null, null, true, 'https://dnd.su/items/5504-horn-of-beckoning-death/', 'Honor among Thieves'),
      ('red-wizard-blade', 'Клинок Красного Волшебника', 'Выкованный Красными Волшебниками по известной только им технологии, этот мрачный стальной кинжал берёт свою силу с Негативного плана. Когда вы попадаете по существу рукопашной атакой этим магическим кинжалом, цель получает дополнительно 3к12 урона некротической энергией.

Существо, чьи хиты опущены этим оружием до 0, умирает, и не может быть воскрешено. Воскресить такое существо может только божество или существо, накладывающее [истинное воскрешение [true resurrection]](/spells/125-true_resurrection/) посредством [скрижали повторного пробуждения [tablet of reawakening]](/items/5502-tablet_of_reawakening/).', 'weapon', 'legendary', null, null, '1-handed', false, 'https://dnd.su/items/5503-red-wizard-blade/', 'Honor among Thieves'),
      ('tablet-of-reawakening', 'Скрижаль повторного пробуждения', 'Эту Крошечную каменную табличку создали Ведьмы Рашемена в противовес некромантии Красных Волшебников. Действием вы можете наложить посредством скрижали [истинное воскрешение [true resurrection]](/spells/125-true_resurrection/), после чего скрижаль уничтожается, рассыпавшись в прах.', 'wondrous', 'legendary', null, null, null, false, 'https://dnd.su/items/5502-tablet-of-reawakening/', 'Honor among Thieves')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Honor among Thieves)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
