-- Migration 080 — dnd.su items seed: Lost Mine of Phandelver.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('dragonguard', 'Драконий страж', 'На этой кирасе +1 изображен золотой дракон. Созданная для героя Невервинтера, человека по имени Тергон, она позволяет владельцу совершать с преимуществом спасброски против дыхания существ, имеющих тип «дракон».', 'armor', 'rare', null, null, 'body', false, 'https://dnd.su/items/274-dragonguard/', 'Lost Mine of Phandelver'),
      ('hew', 'Рассекатель', 'На навершии топора дварфийскими рунами написано «Рассекатель», и ржавчина на нём обманчива. Рассекатель — это боевой топор +1, который наносит максимальный урон, если владелец атакует растение или деревянный предмет. Создателем топора был дварф-кузнец, который враждовал с дриадами из леса, в котором он рубил дрова. Тот, кто несёт этот топор, чувствует тревогу, когда идёт через лес.', 'weapon', 'uncommon', null, null, '1-handed', false, 'https://dnd.su/items/304-hew/', 'Lost Mine of Phandelver'),
      ('lightbringer', 'Светоносная', 'Эта булава +1 была сделана для жреца Латандера, бога рассвета. Навершие булавы имеет форму солнечных лучей и сделано из латуни. Названная Светоносной, эта булава светится как факел, когда этого захочет владелец. Когда булава светится, она наносит Нежити дополнительно 1к6 урона излучением.', 'weapon', 'uncommon', null, null, '1-handed', false, 'https://dnd.su/items/273-lightbringer/', 'Lost Mine of Phandelver'),
      ('spider-staff', 'Посох паука', 'Навершие этого чёрного адамантинового посоха выполнено в форме паука. Посох весит 6 фунтов. Вы должны быть настроены на посох, чтобы получить все его преимущества и накладывать заключённые в посохе заклинания.

Посох можно использовать как боевой посох. Он причиняет дополнительный урон ядом 1к6 при попадании, когда используется как оружие.

У посоха есть 10 зарядов, которые расходуются на применение заключённых в нём заклинаний. Когда посох находится в руке, вы можете действием наложить одно из следующих заклинаний, при условии, что оно есть списке заклинаний вашего класса: [_паук [spider climb]_](/spells/226-spider_climb/) (1 заряд) или [_паутина [web]_](/spells/227-web/) (2 заряда, Сл спасброска от заклинания 15). Для накладывания заклинаний не требуется никаких компонентов.

Посох восстанавливает 1к6 + 4 израсходованных зарядов каждый день на закате. Если вы израсходовали последний заряд, бросьте к20. Если выпадет 1, посох будет уничтожен и рассыпается в пыль.', 'magic-item', 'rare', null, null, null, true, 'https://dnd.su/items/267-spider-staff/', 'Lost Mine of Phandelver')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Lost Mine of Phandelver)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
