-- Migration 081 — dnd.su items seed: Monstrous Compendium.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('nightbringer', 'Приносящая ночь', 'У этой тяжелой булавы рукоять из темного дуба и головка из черненой стали, отделанная золотом. В бою головка булавы окутывается черной энергией.

Вы получаете бонус +3 к броскам атаки и урона, сделанным этим оружием. Когда вы попадаете в цель, используя это оружие, цель получает дополнительные 4к4 урона излучением.

Если у вас злое мировоззрение, то при использовании Приносящей ночи вы получаете следующие преимущества:

**_Благословение королевы драконов_**. Вы невосприимчивы к состояниям очарования и испуга, а также получаете иммунитет к одному из следующих типов повреждений (выбирается когда вы настраиваетесь на оружие): кислота, холод, огонь, электричество или яд.

**_Глаза полуночи_**. Вы обладаете тёмным зрением на расстоянии в 60 футов. Если у вас уже есть темное зрение, его расстояние увеличивается на 60 футов.

**_Полуночный саван_**. Оружие имеет 6 зарядов. Когда вы попадаете по существу атакой с помощью этого оружия, вы можете потратить один заряд, чтобы заставить его совершить спасбросок телосложения Сл 20. При провале, существо ослеплено до начала вашего следующего хода. Оружие восстанавливает 1к6 потраченных зарядов ежедневно на рассвете.', 'weapon', 'legendary', null, null, '1-handed', true, 'https://dnd.su/items/5347-nightbringer/', 'Monstrous Compendium')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Monstrous Compendium)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
