-- Migration 082 — dnd.su items seed: Mordenkainen's Tome of Foes.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('greater-silver-sword', 'Двуручный серебряный меч', 'Вы получаете бонус +3 к броскам атаки и урона, совершённым этим магическим оружием. Пока вы держите меч в руках, вы совершаете с преимуществом спасброски Интеллекта, Мудрости и Харизмы, обладаете иммунитетом к очарованию и сопротивлением урону психической энергией. Более того, если вы совершаете критическое попадание по астральному телу существа, вместо нанесения урона вы можете оборвать серебряную нить, ведущую к материальному телу существа.', 'weapon', 'legendary', null, null, '2-handed', true, 'https://dnd.su/items/2357-greater-silver-sword/', 'Mordenkainen''s Tome of Foes'),
      ('infernal-tack', 'Инфернальный набор для верховой езды', 'Вы можете, использовав действие, призвать [кошмара [nightmare]](/bestiary/252-nightmare/), снаряжённого инфернальным набором, постучав шпорами друг о друга или пройтись ими по кровавой луже. В начале вашего следующего хода, в пределах 20 футов от вас, появляется кошмар. Конь служит вам союзником и начинает свой ход при вашем значении инициативы. Конь остаётся c вами на 1 день, пока либо вы, либо он не умрёте, или пока вы не отпустите его, потратив действие. Если кошмар умрёт, то в течение 24 часов он преобразуется в Девяти Преисподних, и после этого, вы сможете призвать его снова.

Набор для верховой езды не появляется просто так у кошмара. Тот, кто хочет подчинить себе коня, для начала должен обуздать самого коня и, принудительно навесить седло на него. Ни один кошмар не примет добровольно такую вынужденную службу, однако, некоторые со временем формируют сильную привязанность к своим хозяевам и становятся верными спутниками.', 'wondrous', 'legendary', null, null, null, true, 'https://dnd.su/items/2358-infernal-tack/', 'Mordenkainen''s Tome of Foes')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Mordenkainen''s Tome of Foes)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
