-- Migration 084 — dnd.su items seed: Out of the Abyss.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('dawnbringer', 'Несущая Рассвет', '_Несущая Рассвет_ – это позолоченная рукоятка длинного меча, которая была затеряна в Подземье в течение веков. Держа рукоять, вы можете бонусным действием вызвать лезвие из чистого света, льющегося из рукоятки, или заставить его исчезнуть. _Несущая Рассвет_ обладает всеми свойствами [солнечного клинка [sun blade]](/items/217-sun_blade/).

Держа оружие вы можете потратить действие на то, чтобы коснуться лезвием существа и таким образом наложить на него заклинанием [малое восстановление [lesser restoration]](/spells/155-lesser_restoration/). Использовав эту способность вы не сможете воспользоваться ей до следующего рассвета.

**_Разумность._** _Несущая Рассвет_ – это разумное оружие нейтрально-доброго мировоззрения с показателями Интеллекта 12, Мудрости 15 и Харизмы 14. Оно способно слышать и обладает тёмное зрением в радиусе 120 футов.

Меч понимает, читает и говорит на Общем и может общаться с владельцем телепатически. Обладает добрым женским голосом. Он также владеет всеми языками, которыми владеете вы, пока остаетесь настроенным к мечу.

**Личность.** _Несущая Рассвет_ , выкованная древними служителями солнца, создана для того, чтобы нести свет во тьму и сражаться с порождениями тьмы. Она добра и милосердна к страждущим, но жестока и беспощадна к своим врагам.

Многие годы, проведенные в тьме, заставили Несущую Рассвет бояться тьмы и одиночества. Она желает, чтобы её лезвие непрерывно освещало тьму, и против того, чтобы разлучаться со своим носителем на какой бы то ни было промежуток времени.', 'weapon', 'legendary', null, null, '1-handed', true, 'https://dnd.su/items/2375-dawnbringer/', 'Out of the Abyss'),
      ('piwafwi-cloak-of-elvenkind', 'Пивафви (Эльфийский плащ)', 'Это темный плащ из паучьего шелка изготовленный дроу. Это [эльфийский плащ [cloak of elvenkind]](/items/261-cloak_of_elvenkind/). Он теряет свои магические свойства, если в течение 1 часа непрерывно находится на солнечном свете.', 'wondrous', 'uncommon', null, null, null, true, 'https://dnd.su/items/2377-piwafwi-cloak-of-elvenkind/', 'Out of the Abyss'),
      ('piwafwi-of-fire-resistance', 'Пивафви сопротивления огню', 'Это [эльфийский плащ [cloak of elvenkind]](/items/261-cloak_of_elvenkind/). Он также даёт сопротивление урону огнём, пока вы его носите. Он теряет свои магические свойства если в течение 1 часа непрерывно находится на солнечном свете.', 'wondrous', 'rare', null, null, null, true, 'https://dnd.su/items/2376-piwafwi-of-fire-resistance/', 'Out of the Abyss'),
      ('stonespeaker-crystal', 'Говорящий с камнями кристалл', 'Девятнадцатидюймовый осколок кварца, созданный каменными гигантами библиотекарями Грейвенхоллоу, даёт вам преимущество при проверках Интеллекта (Расследование), пока находится у вас.

У кристалла 10 зарядов. Держа его, вы можете потратить действие, чтобы использовать часть его зарядов для накладывания с его помощью одного из хранящихся в нем заклинаний: [разговор с животными [speak with animals]](/spells/292-speak_with_animals/) (2 заряда), [разговор с мёртвыми [speak with dead]](/spells/293-speak_with_dead/) (4 заряда), [разговор с растениями [speak with plants]](/spells/294-speak_with_plants/) (3 заряда).

Когда вы накладываете заклинание школы Прорицания, вы можете использовать кристалл вместо одного материального компонента, который в обычном случае потреблялся бы этим заклинанием, ценой в 1 заряд за каждый уровень заклинания. Кристалл не поглощается заклинанием при таком использовании.

Кристалл восстанавливает 1к6 + 4 израсходованных зарядов ежедневно на рассвете. Если вы истратили последний заряд кристалла, совершите бросок к20. При результате 1, кристалл обращается в пыль и исчезает навсегда.', 'wondrous', 'rare', null, null, null, true, 'https://dnd.su/items/2371-stonespeaker-crystal/', 'Out of the Abyss'),
      ('wand-of-viscid-globs', 'Волшебная палочка вязких шаров', 'Эта тонкая, чёрная, изготовленная темными эльфами палочка имеет 7 зарядов. Держа её, вы можете потратить действие на то, чтобы использовать 1 её заряд, и тогда из её наконечника образуется маленький шар липкого вещества и устремится к существу, находящемуся на расстоянии до 60 футов от вас. Совершите бросок атаки дальнего боя против цели, её модификатор равен вашему модификатору заклинательной характеристики (или вашему модификатору Интеллекта, если у вас нет заклинательной характеристики) плюс бонус мастерства. При попадании шар обволакивает цель и высыхает на ней, что делает цель опутанной на 1 час. Затем вязкое вещество ломается и рассыпается.

Пинта алкоголя полностью разрушает шар, и этот же эффект последует при применении [масла эфирности [oil of etherealness]](/items/135-oil_of_etherealness/) или [универсального растворителя [universal solvent]](/items/243-universal_solvent/). Шар также мгновенно разрушается, если попадает под солнечный свет. Разрушить этот вязкий материал любым другим немагическим способом невозможно, пока он не распадется сам собой.

Палочка восстанавливает 1к6+1 израсходованных зарядов ежедневно в полночь. Если вы истратили последний заряд палочки, совершите бросок к20. При результате 1, палочка будет навсегда уничтожена и превращается в безвредную слизь. Палочка вязких шаров уничтожается спустя 1 час непрерывного нахождения на солнечном свете.', 'magic-item', 'rare', null, null, null, true, 'https://dnd.su/items/2372-wand-of-viscid-globs/', 'Out of the Abyss')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Out of the Abyss)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
