-- Migration 085 — dnd.su items seed: Phandelver and Below: The Shattered Obelisk.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('bracers-of-celerity', 'Наручи стремительности', 'Эта пара лёгких бронзовых наручей отделана мягким пурпурным бархатом и украшена выгравированными закрученными узорами.

Пока вы носите эти наручи, все ваши скорости увеличиваются на 10 футов, и вы совершаете с преимуществом спасброски, совершаемые для того чтобы избежать или прекратить состояние паралича или состояние опутанности на себе.', 'wondrous', 'rare', null, null, null, true, 'https://dnd.su/items/6693-bracers-of-celerity/', 'Phandelver and Below: The Shattered Obelisk'),
      ('cape-of-enlargement', 'Плащ увеличения', 'По краю этой серовато-фиолетовой накидки серебряной нитью вышиты древние руны.

Накидка имеет 3 заряда. Бонусным действием, пока вы носите плащ, вы можете потратить 1 из его зарядов, чтобы увеличить себя, получив следующие преимущества:

Ваш размер увеличивается на одну категорию — например, со Среднего до Большого. Если для увеличения вашего размера на одну категорию недостаточно места, вместо этого вы становитесь максимально возможным размером в доступном пространстве.
Вы совершаете проверки и спасброски Силы с преимуществом.
Когда вы попадаете броском атаки с использованием оружия или безоружным ударом, вы можете добавить свой бонус мастерства к урону от атаки.

Эти преимущества действуют в течение 10 минут или до тех пор, пока вы бонусным действием не отмените их. Накидка ежедневно на рассвете восстанавливает 1к3 израсходованных зарядов.', 'wondrous', 'very-rare', null, null, null, true, 'https://dnd.su/items/6694-cape-of-enlargement/', 'Phandelver and Below: The Shattered Obelisk'),
      ('flayer-slayer', 'Гроза свежевателей', 'Металлическое лезвие этой секиры украшено резными изображениями обезглавленных свежевателей разума. Вы получаете бонус +1 к броскам атаки и урона, совершённых этой секирой.

Аберрация, по которой попали этой секирой получает дополнительный 1к12 рубящего урона. Если Аберрация в данный момент схватила существо, она должна преуспеть в спасброске Силы Сл 15 или отпустит каждое существо, которое она схватила.', 'weapon', 'rare', null, null, '1-handed', true, 'https://dnd.su/items/6695-flayer-slayer/', 'Phandelver and Below: The Shattered Obelisk'),
      ('luminous-war-pick', 'Сияющий клевец', 'Рукоять этого клевца инкрустирована измельченными перламутровыми камнями, которые придают оружию слабое свечение. Вы получаете бонус +1 к броскам атаки и урона, совершённых с помощью этого клевца.

Удерживая клевец, вы можете бонусным действием наложить заклинание [дневной свет [daylight]](/spells/58-daylight/), выбрав точкой на клевце. Использовав это бонусное действие, его нельзя будет использовать снова до следующего рассвета.', 'weapon', 'rare', null, null, '1-handed', true, 'https://dnd.su/items/6696-luminous-war-pick/', 'Phandelver and Below: The Shattered Obelisk'),
      ('mindblasting-cap', 'Мозговая шапка', 'Эта мягкая фиолетовая шапочка украшена вышивкой в виде извилин мозга.

Бонусным действием, когда на вас надета эта шапка, вы можете излучить психическую энергию в виде 60-футового конуса. Каждое существо в этой области должно совершить спасбросок Интеллекта Сл 15. При провале существо получает 5к8 психического урона и становится ошеломлённым на 1 минуту. В случае успеха существо получает вдвое меньше урона. В конце каждого своего хода ошеломлённое существо может повторить спасбросок, оканчивая состояние ошеломления на себе при успехе.

После того, как это бонусное действие будет совершено, его нельзя будет совершить снова до следующего рассвета.', 'wondrous', 'very-rare', null, null, null, true, 'https://dnd.su/items/6730-mindblasting-cap/', 'Phandelver and Below: The Shattered Obelisk'),
      ('mindguard-crown', 'Корона стража разума', 'Пока вы носите эту адамантиновую корону, вы совершаете спасброски Интеллекта, Мудрости и Харизмы с преимуществом, а также вы получаете сопротивление урону психической энергией.', 'wondrous', 'very-rare', null, null, null, true, 'https://dnd.su/items/6731-mindguard-crown/', 'Phandelver and Below: The Shattered Obelisk'),
      ('mudslick-tower', 'Грязевая башня', 'Вы можете действием положить эту гранитную сферу диаметром 1 дюйм на землю и произнести её командное слово, которое на Терране означает «окаменение». Сфера быстро вырастает в толстую башню, которая остается до тех пор, пока вы действием не прикоснетесь к башне и снова не произнесете командное слово, после чего башня снова сжимается до гранитной сферы диаметром 1 дюйм. Чтобы уменьшиться таким образом, башня должна быть пустой. Башня усеяна грязными выступами, которые постоянно выдвигаются и втягиваются по ее поверхности, как будто башня дышит сквозь слой густой грязи.

Каждое существо в области, где появляется башня, должно совершить спасбросок Ловкости Сл 15, получая 10к10 дробящего урона при провале или половину этого урона при успехе. В любом случае существо выталкивается на незанятое место снаружи, но рядом с башней. Объекты в этой области, которые никто не несёт и носит, получают этот урон и автоматически толкаются.

Всякий раз, когда она расширяется, грязевая башня сливается с любым природным камнем, которого она касается, неуклюже наклоняясь и вклиниваясь, чтобы коснуться как можно большего количества природного камня.

Башня имеет ширину 20 футов и высоту 30 футов, с бойницами со всех сторон и зубчатыми стенами наверху. Её интерьер разделен на два этажа, соединенных между собой лестницей, проходящей вдоль одной стены. Лестница заканчивается люком, ведущим на крышу. При активации башня имеет небольшую дверь на стороне, обращенной к вам. Дверь открывается только по вашей команде, которую вы можете произнести бонусным действием. Она невосприимчива к заклинанию [открывание [knock]](/spells/217-knock/) и подобной магии, например, к [колокольчику открывания [chime of opening]](/items/91-chime_of_opening/).

Хотя башня выглядит как камень, она сделана из адамантина, и его магия не позволяет существам опрокинуть её. Крыша, дверь и стены имеют по 100 хитов каждая, иммунитет к урону от немагического оружия, за исключением осадных орудий, и сопротивление всем остальным видам урона. Будучи слитой с натуральным камнем, грязевая башня обладает иммунитетом ко всем повреждениям. Только заклинание [исполнение желаний [wish]](/spells/124-wish/) может восстановить башню (это использование заклинания считается копированием заклинания 8-го уровня или ниже). Каждое накладывание [исполнение желаний [wish]](/spells/124-wish/) заставляет крышу, дверь или одну стену восстанавливать 50 хитов.', 'wondrous', 'very-rare', null, null, null, true, 'https://dnd.su/items/6732-mudslick-tower/', 'Phandelver and Below: The Shattered Obelisk'),
      ('potion-of-psionic-fortitude', 'Зелье псионической стойкости', 'Когда вы выпиваете это зелье, в течение 1 часа вы совершаете с преимуществом спасброски, совершаемые для избегания или снятия с себя эффекта очарования или ошеломления.

Это чёрное зелье переливается мерцающими розовыми и фиолетовыми пятнами.', 'consumable', 'uncommon', null, null, null, false, 'https://dnd.su/items/6733-potion-of-psionic-fortitude/', 'Phandelver and Below: The Shattered Obelisk'),
      ('ring-of-the-orator', 'Кольцо оратора', 'Это кольцо имеет 6 зарядов. Пока вы носите его, вы можете потратить 1 из его зарядов, чтобы в течение 1 минуты ваш голос был четко слышен всем существам в радиусе 1 мили от вас, независимо от постороннего шума. Магическая тишина, 1 фут камня, 1 дюйм обычного металла, тонкий лист свинца или 3 фута дерева блокируют эту проекцию. Если вы проецируете свой голос, говоря на языке, который слушающие существа не понимают, вы можете заставить существ понять, что вы говорите. Вы должны видеть существ, чтобы они могли понять. Кольцо восстанавливает 1к6 израсходованных зарядов ежедневно на рассвете.', 'magic-item', 'uncommon', null, null, 'ring', true, 'https://dnd.su/items/6734-ring-of-the-orator/', 'Phandelver and Below: The Shattered Obelisk'),
      ('staff-of-defense', 'Посох защиты', 'Этот тонкий полый посох сделан из стекла, но прочен, как дуб. Он весит 3 фунта. Пока вы держите посох, вы получаете бонус +1 к вашему Классу Доспеха.

**_Заклинания._** Посох имеет 10 зарядов. Удерживая его, вы можете потратить необходимое количество зарядов для накладывания одного из следующих заклинаний посоха: [доспехи мага [mage armor]](/spells/60-mage_armor/) (1 заряд) или [щит [shield]](/spells/70-shield/) (2 заряда).

Посох восстанавливает 1к6 + 4 израсходованных заряда ежедневно на рассвете. Если вы потратите последний заряд посоха, бросьте к20. При выпадении «1» посох разбивается и уничтожается.', 'magic-item', 'rare', null, null, null, true, 'https://dnd.su/items/6736-staff-of-defense/', 'Phandelver and Below: The Shattered Obelisk')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Phandelver and Below: The Shattered Obelisk)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
