-- Migration 086 — dnd.su items seed: Planescape: Adventures in the Multiverse.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('mimir', 'Мимир', 'Это устройство в форме черепа наполнено знаниями. Устройство весит 5 фунтов и покрыто тонкой гравировкой планарных сигилов.

Бонусным действием вы можете подбросить устройство в воздух, после чего оно начнёт парить на расстоянии 1к3 фута от вас и вы сможете получить доступ к его свойствам. Пока Мимир парит, существо, отличное от вас, может действием попытаться схватить или связать устройство, либо успешно совершив безоружный удар против КД 22, либо успешную проверку Ловкости (Акробатика) Сл 22. Вы можете бонусным действием схватить и спрятать устройство.

Устройство имеет КД 22, 25 хитов, иммунитет к яду и психическому урону, а также сопротивление другим видам урона. Считается, что это носимый предмет, пока он парит рядом с вами.

**_Эзотерические знания._** Пока устройство парит, вы можете действием наложить [знание легенд [legend lore]](/spells/115-legend_lore/) устройством. Устройство произносит раскрытые знания вслух. После того, как это свойство будет использовано, его нельзя будет использовать снова до следующего рассвета.

**_Планарное знание._** Устройство знает основную полезную информацию о планах существования. Пока устройство парит, оно устно отвечает на вопросы, которые вы или кто-либо, кого вы выбираете, задаете ему по этой теме. Он знает информацию о планах из _«Руководства Мастера»_ , а также базовую информацию о городах-воротах Внешних земель.', 'wondrous', 'rare', null, null, null, true, 'https://dnd.su/items/6914-mimir/', 'Planescape: Adventures in the Multiverse'),
      ('portal-compass', 'Портальный компас', 'Этот портативный магический инструмент указывает в направлении последнего портала, через который он прошёл, пока он и портал находятся на одном плане существования. Если этого портала больше не существует, стрелка становится неподвижной, пока компас не пройдёт через новый портал.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/6915-portal-compass/', 'Planescape: Adventures in the Multiverse'),
      ('sensory-stone', 'Сенсорный камень', 'Этот маленький гладкий камень содержит суть какого-либо опыта.

Действием вы или обозначенное вами добровольное существо можете коснуться камня и испытать ощущение, как если бы это произошло с указанным существом. Иллюзорный опыт мимолетен и безвреден, каким бы реальным он ни казался в данный момент.

**_Запись ощущения._** Вы можете реакцией записать короткое ощущение длительностью не более 6 секунд, испытываемое существом по вашему выбору в пределах 30 футов от вас, вливая суть этого опыта в камень. Это заменяет любые ощущения, уже сохранённые в камне.

**_Перекачка_**** _ощущения._** Бонусным действием вы можете использовать магию камня, чтобы снять с себя состояние очарования или испуга, уничтожив при этом камень.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/6916-sensory-stone/', 'Planescape: Adventures in the Multiverse')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Planescape: Adventures in the Multiverse)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
