-- Migration 089 — dnd.su items seed: Spelljammer: Adventures in Space.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('fish-suit', 'Костюм рыбы', 'Этот громоздкий костюм, полностью закрывающий ваши тело и голову, надевается и снимается за 1 минуту. Пока он надет, то позволяет вам дышать в безвоздушной среде и даёт вам иммунитет к вредному воздействию любого окружающего вас газа. Кроме того, под водой костюм даёт вам скорость плавания, равную вашей скорости ходьбы, а в среде без гравитации — скорость полёта, равную вашей скорости ходьбы.', 'wondrous', 'very-rare', null, null, null, false, 'https://dnd.su/items/4388-fish-suit/', 'Spelljammer: Adventures in Space'),
      ('spelljamming-helm', 'Магический руль', 'Задача этого богато украшенного сиденья заключается в том, чтобы в воздухе и космосе управлять перемещением корабля, на котором оно установлено. Сиденье также может управлять кораблём и перемещать его по воде или под водой, если он предназначен для подобных перемещений. Такой корабль должен весить не менее 1 тонны.

Ощущение настройки на _магический руль_ похоже на покалывание, которые вы испытываете, когда затекает рука или нога, но менее болезненно.

Пока вы настроены на _магический руль_ и сидите на нём, вы получаете следующие преимущества, пока поддерживаете концентрацию (как если бы вы концентрировались на заклинании):

Вы можете использовать _магический руль_ для перемещения корабля по космосу, воздуху или воде на расстояние вплоть до скорости корабля. Если корабль находится в космосе, и в пределах 1 мили от него нет других объектов весом как минимум в 1 тонну, вы можете использовать _магический руль_ для перемещения корабля со скоростью, достаточной для преодоления 100 миллионов миль за 24 часа.
Вы можете поворачивать корабль, хоть и несколько неуклюже. Это похоже на то, как для маневрирования морским кораблём можно использовать обычный штурвал или вёсла.
В любое время вы можете видеть и слышать, что происходит на корабле и вокруг его, словно вы стоите в выбранном вами месте на борту.

**_Передача настройки._** Вы можете действием коснуться согласного заклинателя. Это существо мгновенно настраивается на _магический руль_ , а ваша настройка на него заканчивается.

### **Стоимость магического руля**

_Магический руль_ управляет кораблём так же, как работают паруса, вёсла и штурвалы на обычном морском корабле, и его легко создать, если у вас есть подходящее заклинание. Для заклинания [сотворение магического руля [creating spelljamming helm]](/spells/4761-creating_spelljamming_helm/) необходим материальный компонент стоимостью 5 000 зм, так что эта сумма является наименьшей, которую заплатят при приобретении магического руля.

У купцов Дикого космоса, включая [доваров [dohwar]](/bestiary/8822-dohwar/) и [мерканов [mercane]](/bestiary/8848-mercane/), цены на магический руль, как правило, сильно больше по сравнению со стоимостью создания руля. Насколько сильно — зависит от рынка, но 7 500 зм выглядят разумной ценой. Отчаявшийся же покупатель на рынке продавца может отдать все 10 000 зм и даже больше.', 'wondrous', 'rare', null, null, null, true, 'https://dnd.su/items/4387-spelljamming-helm/', 'Spelljammer: Adventures in Space'),
      ('wildspace-orrery', 'Теллурий Дикого космоса', 'Находясь в системе Дикого космоса, это переносное магическое устройство автоматически отслеживает положение и движение всех солнц, планет, лун и комет в пределах этой системы и проецирует образы этих тел в их текущих позициях. Среди этих изображений мерцает маленький белый шарик света, указывающий текущее местоположение модели.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/4389-wildspace-orrery/', 'Spelljammer: Adventures in Space')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Spelljammer: Adventures in Space)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
