-- Migration 099 — dnd.su items seed: Unknown D&D supplement (DDHC).
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('anchor-of-seafaring', 'Якорь мореходства', 'Предмет состоит из железного стержня длиной в 2 фута, с поперечиной вверху и двумя загнутыми прутьями внизу. К поперечине привязана толстая лыковая верёвка.
Если действием вы произнесёте командное слово якоря, верёвка волшебным образом начнёт удлиняться, покуда якорь не достигнет дна или верёвка удлинится до своего предела в 1 милю. Верёвка вновь сокращается до 4 футов, если произнести командное слово.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/4683-anchor-of-seafaring/', 'Unknown D&D supplement (DDHC)'),
      ('anklet-of-walking', 'Ножной браслет хождения', 'Пока вы носите этот браслет, вы можете стоять на любой жидкости и ходить по ней, как будто это твёрдая поверхность.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/4642-anklet-of-walking/', 'Unknown D&D supplement (DDHC)'),
      ('bellows-of-breezes', 'Меха ветров', 'Меха выполнены из коричневой кожи и твёрдой древесины, а сопло — из латуни. Действием вы можете накачать меха, отчего в течение 1 минуты из сопла вырывается линия сильного ветра 60 футов длиной и 10 футов шириной.

Существо, начинающее свой ход в области воздействия, должно преуспеть в спасброске Силы Сл 15, иначе будет оттолкнуто на 15 футов по направлению ветра. Существо, двигающееся в области воздействия по направлению к мехам, должно тратить 2 фута скорости за каждый фут передвижения.

Ветер развеивает газы и испарения, а также гасит свечи, факелы и другие сходные незащищённые источники пламени. Огонь в защищённых от ветра местах, таких как фонари, яростно трепещет и гаснет с 50% шансом.

Пока эффект не окончен, в каждый свой ход вы можете бонусным действием менять направление, в которое направлено сопло мехов.

Как только вы использовали эту особенность предмета, она не может быть вновь использована до следующего рассвета.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/4682-bellows-of-breezes/', 'Unknown D&D supplement (DDHC)'),
      ('bottle-of-moonlight', 'Бутыль лунного света', 'Бутыль выполнена из белёсого камня в виде полумесяца. Внутри — густая серебристая жидкость. Если действием налить жидкость на ликантропа, он немедленно обращается в свою звериную форму на 1 час.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/4681-bottle-of-moonlight/', 'Unknown D&D supplement (DDHC)'),
      ('chalice-of-colors', 'Кубок красок', 'Когда этот цветастый стеклянный кубок наполнен водой, действием вы можете выплеснуть содержимое в любом направлении. Жидкость превращается в слепящий поток яркого разноцветного света. Бросьте 6к10; суммарный результат определяет число хитов, на которые распространится эффект. Существа в 15-футовом конусе, исходящем от вас, подвержены эффекту в порядке возрастания их текущих хитов (исключая существ, не способных видеть).

Каждое существо в конусе, начиная с существа с наименьшим числом текущих хитов, ослеплено до конца вашего следующего хода. Вычтите число хитов из общей суммы перед переходом к следующему; число хитов существа должно быть меньше или равно оставшемуся от суммы числа, иначе оно не будет ослеплено.

Как только вы использовали эту особенность предмета, оно не может быть вновь использовано до следующего рассвета.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/4680-chalice-of-colors/', 'Unknown D&D supplement (DDHC)'),
      ('chitinous-armor', 'Хитиновый доспех', 'Доспех состоит из плаща и леггинсов, выполненных из рыбьей кожи, покрытой перекрывающимися кусками хитина гигантских крабов. Вы можете дышать под водой, пока носите этот доспех. Во всех остальных аспектах он идентичен чешуйчатому доспеху.', 'wondrous', 'uncommon', null, null, null, false, 'https://dnd.su/items/4644-chitinous-armor/', 'Unknown D&D supplement (DDHC)')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Unknown D&D supplement (DDHC))',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
