-- Migration 100 — dnd.su items seed: Van Richten's Guide to Ravenloft.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('harkons-bite', 'Укус Харкона', 'Жуткий волчий зуб свисает с этого простого шнуркового ожерелья. Пока вы его носите, оно даёт вам бонус +1 к проверкам характеристик и спасброскам._
_

**_Проклятие._** Настройка на _у_ _кус Харкона_ проклинает вас до тех пор, пока либо Харкон Лукас не снимет с вас это ожерелье, либо пока проклятие не будет снято при помощи заклинания [снятие проклятия [remove curse]](/spells/326-remove_curse/) или подобной магии. Пока вы остаётесь проклятым, вы не можете снять это ожерелье.

Надевание или снятие ожерелья, в независимости от того, настраиваетесь вы на него или нет, вы поражаетесь [ликантропией вервольфа](/articles/bestiary/45-likantropy/), как описано в _«Бестиарии»_. Это проклятие действует до рассвета после следующего полнолуния. Если после этого вы всё ещё будете в ожерелье, то вы снова поражаетесь ликантропией.', 'wondrous', 'uncommon', null, null, null, true, 'https://dnd.su/items/2234-harkons-bite/', 'Van Richten''s Guide to Ravenloft'),
      ('nepenthe', 'Непенте', 'Вы получаете бонус +3 бонуса к атакам и броскам урона, совершённым этим магическим оружием. Когда вы попадаете атакой по исчадию или нежити, оно дополнительно получает 2к10 урона излучением.

Пока вы держите обнаженный меч, он создает вокруг вас ауру радиусом 10 футов. Вы и все дружественные вам существа, находящиеся в ауре, получаете преимущество для спасбросков совершаемых против заклинаний и других магических эффектов. Если вы имеете 17 или более уровней в классе паладина, радиус ауры увеличивается до 30 футов.

**_Разум._**_Непенте_ \- это разумное оружие нейтрально злого мировоззрения с Интеллектом 10, Мудростью 8 и Харизмой 18. Оно обладает слухом и тёмным зрение на расстоянии 60 футов. Оно умеет читать и понимает Эльфийский. Оно также может говорить на Эльфийском, но только голосом своего владельца, с которым меч может общаться с помощью телепатии.

**_Индивидуальность._** За свою жизнь меч обезглавил тысячи преступников, не все из которых были виновны в преступлениях, за которые они были осуждены. Меч не может отличить виновного от невинного, и с каждым обезглавливанием он всё больше жаждет справедливости и крови. Меч развращен и неисправим.', 'weapon', 'legendary', null, null, '1-handed', true, 'https://dnd.su/items/2235-nepenthe/', 'Van Richten''s Guide to Ravenloft')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Van Richten''s Guide to Ravenloft)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
