-- Migration 101 — dnd.su items seed: Vecna: Eve of Ruin.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('chime-of-exile', 'Колокольчик изгнания', 'Серебряный колокольчик покрыт выгравированными на нем магическими символами. Пока вы держите колокольчик, действием вы можете наложить заклинание [изгнание [banishment]](/spells/116-banishment/) (Сл спасброска 20). Если цель заклинания имеет 50 хитов или меньше, то она автоматически проваливает спасбросок. После того, как колокольчик был использован для наложения заклинания, он не может быть использован таким образом до следующего рассвета.', 'wondrous', 'very-rare', null, null, null, false, 'https://dnd.su/items/9135-chime-of-exile/', 'Vecna: Eve of Ruin'),
      ('crown-of-lies', 'Корона лжи', 'Предав и едва не уничтожив лича Векну, воин Кас оказался заперт в Царстве теней. Заключенный в Домен ужаса под названием Товаг, он изнывал в облике вампира, пока Тёмные силы Царства теней не заманили Каса в сокрытую кузницу, где он обнаружил корону лжи. Кас поклялся отдать Векну прямо им в руки, после чего надел артефакт и был отпущен. Он намеревается уничтожить своего бывшего господина. Если Кас потерпит неудачу, то Тёмные силы вернут его обратно.

Корона выполнена из отполированных и переплетенных металлических прутьев. Чтобы настроиться на неё, нужно поместить её на голову и произнести истинное желание своего сердца. Вы узнаете, как настроиться на корону, когда прикоснётесь к ней.

**_Случайные свойства._** Корона лжи обладает [несколькими свойствами](https://dnd.su/articles/inventory/139-artifacts/), определяемыми случайным образом:

1 малое положительное свойство
1 основное положительное свойство
1 малое отрицательное свойство

**_Совершенная маскировка._** Пока настроены на корону, вы можете действием превратиться в любое существо, которое вы видели хотя бы раз и чей размер не более чем на одну категорию меньше или больше вашего.

Новый облик в точности повторяет внешность выбранного существа, включая голос. Ваши размеры и скорость заменяются на его. В остальном вы сохраняете свою игровую статистику. Пока вы находитесь в новом облике, корона сливается с вашей личиной и не поддается обнаружению.

Ваш новый облик существует до тех пор, пока вы не умрёте, не закончите настройку на корону или не используете действие, чтобы превратиться в иное существо или вернуться в свой истинный облик. Взаимодействие с вами, пока вы преображены короной, не раскрывает магию иллюзий и не показывает ничего, кроме подробностей о существе, которое вы копируете. Вы считаетесь выбранным существом для целей заклинаний, ловушек и других защит, которые не были бы направлены против него.

Когда вы находитесь в новом облике, любая ваша ложь всегда кажется правдой, независимо от того, какие магические или немагические методы используются для её обнаружения. Вы получаете заклинания [послание [sending]](/spells/256-sending/), адресованные вам и существу, которое вы копируете. Заклинание [наблюдение [scrying]](/spells/176-scrying/) и другие подобная магия, направленные на копируемое существо, будет выбирать целью вас. Единственный способ раскрыть ваш истинный облик, пока вы преображены короной — накладывание заклинания [исполнение желаний [wish]](/spells/124-wish/).

Нося корону в своём истинном облике, вы можете выбрать, чтобы корона была видна, если пожелаете.

**_Уничтожение короны._** Если существо, носящее корону, будет убито существом, которое оно копирует, то корона распадётся и будет уничтожена.', 'wondrous', 'artifact', null, null, null, true, 'https://dnd.su/items/9133-crown-of-lies/', 'Vecna: Eve of Ruin'),
      ('rod-of-seven-parts', 'Жезл семи частей', 'Много веков назад война между первобытными существами и богами избороздила планы существования. Лорд демонов по имени [паук-волк Миска [miska the Wolf-Spider]](/bestiary/15726-miska_the_wolf_spider/) в конце концов поставил первозданных врагов на грань уничтожения.

Отчаявшись спасти себя и своих союзников, против Миски восстали могущественные существа-элементали, называемые Князьями Ветра Ааки. Приверженцы концепции закона, герцоги ветра происходят от народа ваати, который когда-то правил многими мирами. Семь герцогов Ветра вплели свою силу в артефакт, названный **жезлом закона [rod of law]**. Герцоги использовали его, чтобы заточить Миску на плане Пандемониум. В результате жезл распался на семь частей, которые были разбросаны по всей мультивселенной. Таким образом, артефакт стал известен как **жезл закона [rod of law]**.

**_Владение сломанным жезлом._** На жезл нельзя настроиться, пока он сломан. Держа в руках одну часть сломанного жезла, вы знаете общее местоположение следующей за ней части, так как жезл жаждет стать цельным. Действием несколько частей артефакта можно собрать в единое целое или разобрать, хотя частично собранный жезл не приобретает никаких дополнительных особенностей.

Кроме того, пока вы держите одну часть сломанного жезла, вы можете действием наложить заклинание, связанное с этой частью, как указано в таблице «Части жезла». После того как часть жезла была использована для наложения заклинания, она не может быть использована таким образом до следующего рассвета.

__

Часть|  Заклинание
---|---
[Первая часть](https://dnd.su/items/9138-rod_of_seven_parts_first_part_/)| [общение [commune]](/spells/198-commune/)
[Вторая часть](https://dnd.su/items/9139-rod_of_seven_parts_second_part_/)| [магические врата [arcane gate]](/spells/150-arcane_gate/)
[Третья часть](https://dnd.su/items/9140-rod_of_seven_parts_third_part_/)| [изменение тяготения [reverse gravity]](/spells/120-reverse_gravity/) (Сл спасброска 18)
[Четвёртая часть](https://dnd.su/items/9141-rod_of_seven_parts_fourth_part_/)| [регенерация [regenerate]](/spells/302-regenerate/)
[Пятая часть](https://dnd.su/items/9142-rod_of_seven_parts_fifth_part_/)| [поиск пути [find the path]](/spells/245-find_the_path/)
[Шестая часть](https://dnd.su/items/9144-rod_of_seven_parts_sixth_part_/)| [таинственный мираж [mirage arcane]](/spells/343-mirage_arcane/)
[Седьмая часть](https://dnd.su/items/9145-rod_of_seven_parts_seventh_part_/)| [подобие [simulacrum]](/spells/237-simulacrum/)

**_Владение всем жезлом._** Как только все семь частей будут собраны, существо может настроиться на жезл семи частей. Как только вы сделаете это, то получите следующие преимущества:

**Магическое оружие.** Жезл семи частей можно использовать как магический боевой посох, предоставляющий бонус +3 к броскам атаки и урона им.
**Заклинания.** У жезла семи частей есть 7 зарядов и он ежедневно восстанавливает 1к4 + 3 заряда на рассвете. Пока вы его держите, то можете действием потратить 1 заряд и наложить любое заклинание из таблицы «Части жезла». Вы также можете действием наложить с его помощью заклинание [обнаружение зла и добра [detect evil and good]](/spells/194-detect_evil_and_good/), не тратя зарядов.
**Высший закон.** Если ваше мировоззрение не является законным, то ваш взгляд на мир меняется в сторону соблюдения личного кодекса. Вы склонны выполнять обещания, следовать своему слову и придерживаться своих убеждений.
**Уничтожение жезла.** Единственный способ уничтожить жезл семи частей — погрузить собранный артефакт в Бездне, прямо в реку лавы. Он должен оставаться в ней в течение пятидесяти лет, прежде чем будет окончательно уничтожен.
Таким образом можно временно уничтожить часть жезла, но через год после разрушения она вновь сформируется и телепортируется в случайное место в мультивселенной.

Владение боевым посохом позволит вам добавлять свой бонус мастерства к броскам атаки при любой атаке, которую вы совершаете с его помощью.', 'magic-item', 'artifact', null, null, null, true, 'https://dnd.su/items/9134-rod-of-seven-parts/', 'Vecna: Eve of Ruin')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Vecna: Eve of Ruin)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
