-- Migration 102 — dnd.su items seed: Volo's Guide to Monsters.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('mind-blade', 'Клинок разума', 'В руках любого другого существа клинок разума действует как обычный меч своего типа. В руках предназначенного ему владельца клинок разума становится магическим оружием и дополнительно наносит 2к6 урона психической энергией любой цели, по которой ударит.', 'weapon', 'rare', null, null, '1-handed', true, 'https://dnd.su/items/2360-mind-blade/', 'Volo''s Guide to Monsters'),
      ('mind-carapace-armor', 'Панцирный доспех разума', 'Любой немагический комплект тяжелых доспехов [свежеватели разума [mind flayer]](/bestiary/237-mind_flayer/) могут превратить в панцирный доспех разума. Только одно существо может на него настроиться: либо конкретный свежеватель разума, либо один из их рабов.

Если его носит любое другое существо, то доспех работает как любой обычный доспех своего типа. Для предназначенного ему владельца доспех даёт преимущество на спасброски Интеллекта, Мудрости и Харизмы и даёт владельцу иммунитет к состоянию испуганный.', 'armor', 'uncommon', null, null, 'body', true, 'https://dnd.su/items/2359-mind-carapace-armor/', 'Volo''s Guide to Monsters'),
      ('mind-lash', 'Плеть разума', 'В руках любого кроме [свежевателя разума [mind flayer]](/bestiary/237-mind_flayer/) плеть разума работает как обычный кнут. В руках иллитида это магическое оружие сдирает с существа волю к жизни и плоть, нанося 2к4 дополнительного урона психической энергией при попадании.

Любое существо, которое получило урон психической энергией от плети разума должно успешно совершить спасбросок Мудрости Сл 15 или получить помеху на спасброски Интеллекта, Мудрости или Харизмы на 1 минуту. Существо может повторить спасбросок в конце каждого своего хода, и прекратить эффект при успехе.', 'weapon', 'rare', null, null, '1-handed', true, 'https://dnd.su/items/2361-mind-lash/', 'Volo''s Guide to Monsters'),
      ('shield-of-far-sight', 'Щит Дальнего Взора', 'Если щит дальнего взора уничтожен, то свежеватель разума, который его создал, слепнет на 2к12 часов.', 'armor', 'rare', null, null, 'shield', false, 'https://dnd.su/items/2362-shield-of-far-sight/', 'Volo''s Guide to Monsters')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Volo''s Guide to Monsters)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
