-- Migration 105 — dnd.su items seed: Xanathar's Guide to Everything.
-- Spec-018 T015. Auto-generated by scripts/items-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-dndsu-codegen.ts --emit-migrations
--
-- Idempotency:
--   * NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
-- Source bucket: source_slug='srd-5e' (shared with mig 044/046+);
-- per-book name lives in nodes.fields.source_detail.

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot,
      requires_attunement, dndsu_url, source_detail
    ) as (values
      ('armor-of-gleaming', 'Сверкающий доспех', 'Этот доспех никогда не покрывается грязью.', 'armor', 'common', null, null, 'body', false, 'https://dnd.su/items/425-armor-of-gleaming/', 'Xanathar''s Guide to Everything'),
      ('bead-of-nourishment', 'Бусина насыщения', 'Эта пористая безвкусная студенистая бусина растворяется у вас на языке и насыщает вас на 1 день.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/393-bead-of-nourishment/', 'Xanathar''s Guide to Everything'),
      ('bead-of-refreshment', 'Освежающая бусина', 'Эта пористая безвкусная студенистая бусина растворяется в жидкости, превращая до пинты жидкости в свежую чистую холодную воду. Бусина не оказывает эффект на магические жидкости или опасные вещества типа яда.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/409-bead-of-refreshment/', 'Xanathar''s Guide to Everything'),
      ('boots-of-false-tracks', 'Сапоги ложных следов', 'Только Гуманоиды могут носить эти сапоги. Когда вы их носите, то можете их заставить оставлять следы других Гуманоидов вашего размера.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/424-boots-of-false-tracks/', 'Xanathar''s Guide to Everything'),
      ('candle-of-the-deep', 'Свеча глубин', 'Пламя этой свечи не гаснет при погружении в воду. Она излучает свет и тепло как обычная свеча.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/426-candle-of-the-deep/', 'Xanathar''s Guide to Everything'),
      ('cast-off-armor', 'Доспех быстрого снятия', 'Вы можете снять этот доспех действием.', 'armor', 'common', null, null, 'body', false, 'https://dnd.su/items/397-cast-off-armor/', 'Xanathar''s Guide to Everything'),
      ('charlatans-die', 'Кость шарлатана', 'Когда вы бросаете эту 6-гранную кость, вы можете выбрать, какой гранью она выпадет.', 'wondrous', 'common', null, null, null, true, 'https://dnd.su/items/404-charlatans-die/', 'Xanathar''s Guide to Everything'),
      ('cloak-of-billowing', 'Развевающийся плащ', 'Когда вы носите этот плащ, вы можете бонусным действием заставить его драматично развеваться.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/420-cloak-of-billowing/', 'Xanathar''s Guide to Everything'),
      ('cloak-of-many-fashions', 'Плащ множества стилей', 'Когда вы носите этот плащ, вы можете бонусным действием заставить его изменить стиль, цвет и видимое качество. Вес плаща не меняется. Независимо от внешнего вида, он может быть только плащом.

Хотя он может принимать вид других магических плащей, их свойств он не получает.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/415-cloak-of-many-fashions/', 'Xanathar''s Guide to Everything'),
      ('clockwork-amulet', 'Механистический амулет', 'Этот медный амулет содержит очень маленькие шестерёнки, находящиеся в постоянном движении и заряженные магией Механуса — плана механической предопределённости. Существо, которое прикладывает амулет к уху, может услышать тихое тиканье и шуршание шестерёнок. Когда вы носите этот амулет и совершаете бросок атаки, вы можете не бросать к20 и просто выбрать значение «10» на кости. Это свойство нельзя использовать повторно до следующего рассвета.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/406-clockwork-amulet/', 'Xanathar''s Guide to Everything'),
      ('clothes-of-mending', 'Самочинящаяся одежда', 'Эта элегантная одежда путешественника волшебным образом восстанавливает износ и разрывы. Куски ткани, которые были уничтожены, не могут самостоятельно восстановиться.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/423-clothes-of-mending/', 'Xanathar''s Guide to Everything'),
      ('dark-shard-amulet', 'Амулет тёмного осколка', 'Этот амулет выполнен из цельного осколка упругого экстрапланарного материала, происходящего из царства покровителя вашего колдуна. Пока он надет на вас, вы получаете следующие преимущества:

Вы можете использовать этот амулет как магическую фокусировку для своих заклинаний колдуна.
Вы можете попробовать наложить [заговор](/spells/?search=&level=0&class=20), которого не знаете. Этот заговор должен быть в списке заклинаний колдуна, и вы должны преуспеть в проверке Интеллекта (Магия) Сл 10. При успехе вы накладываете заклинание. При провале и заклинание, и действие, которое было предназначено для накладывания заклинания, теряется. В любом случае вы не можете снова использовать это свойство, пока не завершите продолжительный отдых.', 'wondrous', 'common', null, null, null, true, 'https://dnd.su/items/392-dark-shard-amulet/', 'Xanathar''s Guide to Everything'),
      ('dread-helm', 'Шлем ужаса', 'Этот жуткий стальной шлем заставляет ваши глаза светиться красным, когда вы его носите.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/437-dread-helm/', 'Xanathar''s Guide to Everything'),
      ('ear-horn-of-hearing', 'Слуховой рог', 'Будучи поднесённым к уху, этот рог подавляет на вас эффекты состояния «оглохший» и позволяет слышать нормально.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/428-ear-horn-of-hearing/', 'Xanathar''s Guide to Everything'),
      ('enduring-spellbook', 'Износостойкая книга заклинаний', 'Эта книга заклинаний, включая все в ней записанное, не может быть повреждена огнём или погружением в воду. Кроме того, она не портится со временем.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/400-enduring-spellbook/', 'Xanathar''s Guide to Everything'),
      ('ersatz-eye', 'Запасной глаз', 'Этот искусственный глаз заменяет настоящий, который был потерян или удалён. Когда запасной глаз вставлен в глазницу, его не может удалить никто, кроме вас, и вы можете видеть через этот крошечный шарик, как будто это обычный глаз.', 'wondrous', 'common', null, null, null, true, 'https://dnd.su/items/399-ersatz-eye/', 'Xanathar''s Guide to Everything'),
      ('hat-of-vermin', 'Шляпа вредителей', 'У этой шляпы три заряда. Держа шляпу, вы можете действием потратить один заряд и произнести командное слово, которое по вашему выбору вызовет [летучую мышь [bat]](/bestiary/377-bat/), [лягушку [frog]](/bestiary/380-frog/) или [крысу [rat]](/bestiary/373-rat/). Вызванное существо появляется в шляпе и пытается уйти от вас с максимально возможной скоростью. Существо ни дружественно, ни враждебно, и не находится под вашим контролем. Оно ведёт себя как обычное существо своего вида и исчезает через 1 час или, когда его хиты опускаются до 0. Шляпа восстанавливает все израсходованные заряды ежедневно на рассвете.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/439-hat-of-vermin/', 'Xanathar''s Guide to Everything'),
      ('hat-of-wizardry', 'Шляпа волшебства', 'Эта старинная конусообразная шляпа украшена золотыми полумесяцами и звёздами. Пока она надета на вас, вы получаете следующие преимущества:

Вы можете использовать эту шляпу как заклинательную фокусировку для своих заклинаний волшебника.
Вы можете попытаться наложить [заговор](/spells/?search=&level=0&class=21), которого не знаете. Заговор должен присутствовать в списке заклинаний волшебника, и вы должны преуспеть в проверке Интеллекта (Магия) Сл 10. При успехе вы накладываете заклинание. При провале и заклинание, и действие, которое было предназначено для накладывания заклинания, теряется. В любом случае вы не можете снова использовать это свойство, пока не завершите продолжительный отдых.', 'wondrous', 'common', null, null, null, true, 'https://dnd.su/items/438-hat-of-wizardry/', 'Xanathar''s Guide to Everything'),
      ('hewards-handy-spice-pouch', 'Удобный мешочек специй Хеварда', 'Этот мешочек пуст, и у него 10 зарядов. Держа его в руке, вы можете действием потратить один заряд, назвать любую немагическую пищевую приправу (например, соль, перец, шафран или кинза), и вытащить щепотку приправы из мешочка. Щепотки достаточно, чтобы приправить одну порцию еды. Мешок ежедневно восстанавливает 1к6+4 потраченных зарядов на рассвете.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/435-hewards-handy-spice-pouch/', 'Xanathar''s Guide to Everything'),
      ('horn-of-silent-alarm', 'Рог беззвучного сигнала', 'У этого рога 4 заряда. Когда вы используете действие, чтобы подуть в него, одно существо по вашему выбору может слышать трубный звук рога, при условии, что оно находится не более, чем в 600 футах от рога, и не оглохшее. Никакие другие существа не слышат звук рога. Рог восстанавливает 1к4 потраченных зарядов ежедневно на рассвете.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/421-horn-of-silent-alarm/', 'Xanathar''s Guide to Everything'),
      ('instrument-of-illusions', 'Инструмент иллюзий', 'Когда вы играете на этом музыкальном инструменте, вы можете создавать безвредные иллюзорные визуальные эффекты в пределах сферы радиусом 5 футов с центром на инструменте. Если вы бард, радиус возрастает до 15 футов. Примеры визуальных эффектов: светящиеся ноты в воздухе, призрачная танцовщица, бабочки или медленно падающие хлопья снега. Магические эффекты неосязаемы и не издают звуков, кроме того, их иллюзорность очевидна. Эффекты заканчиваются, когда вы перестаёте играть.', 'wondrous', 'common', null, null, null, true, 'https://dnd.su/items/401-instrument-of-illusions/', 'Xanathar''s Guide to Everything'),
      ('instrument-of-scribing', 'Инструмент надписей', 'У этого инструмента 3 заряда. Играя на нём, вы можете действием потратить один заряд инструмента, чтобы написать магическое послание на немагическом предмете или поверхности, которые вы можете видеть в пределах 30 футов от вас.

Послание не может превышать 6 слов и должно быть написано на известном вам языке. Если вы бард, то можете увеличить длину сообщения ещё на 7 слов, и по вашему выбору слова могут слабо светиться, что позволит прочесть их в немагической темноте. Применение заклинания [рассеивание магии [dispel magic]](/spells/301-dispel_magic/) на слова стирает их. В противном случае сообщение пропадает через 24 часа.

Инструмент восстанавливает все потраченные заряды ежедневно на рассвете.', 'wondrous', 'common', null, null, null, true, 'https://dnd.su/items/402-instrument-of-scribing/', 'Xanathar''s Guide to Everything'),
      ('lock-of-trickery', 'Плутовской замок', 'Этот замок выглядит как обычный замок, и к нему прилагается один ключ. Внутренний механизм замка магическим образом двигается, чтобы предотвратить попытки взлома. Проверки Ловкости с целью вскрыть этот замок совершаются с помехой.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/416-lock-of-trickery/', 'Xanathar''s Guide to Everything'),
      ('moon-touched-sword', 'Осенённый луной меч', 'В темноте обнажённое лезвие этого меча излучает лунный свет, создавая яркий свет в радиусе 15 футов и тусклый свет в радиусе ещё 15 футов.', 'weapon', 'common', null, null, '1-handed', false, 'https://dnd.su/items/410-moon-touched-sword/', 'Xanathar''s Guide to Everything'),
      ('mystery-key', 'Таинственный ключ', 'Головка этого ключа выполнена в виде вопросительного знака. Существует шанс 5%, что ключ откроет любой замок, в который был вставлен. Однажды открыв что либо, ключ пропадает.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/432-mystery-key/', 'Xanathar''s Guide to Everything'),
      ('orb-of-direction', 'Сфера направления', 'Держа эту сферу, вы можете действием определить направление на север. Это свойство работает только на Материальном плане.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/431-orb-of-direction/', 'Xanathar''s Guide to Everything'),
      ('orb-of-time', 'Сфера времени', 'Держа эту сферу, вы можете действием определить время суток на улице (утро, день, вечер или ночь). Это свойство работает только на Материальном плане.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/430-orb-of-time/', 'Xanathar''s Guide to Everything'),
      ('perfume-of-bewitching', 'Парфюм очарования', 'Этот крошечный пузырёк содержит магический парфюм в количестве, достаточном для одного использования. Действием вы можете нанести парфюм на себя, и его эффект будет длиться один час. В течение этого времени вы совершаете с преимуществом все проверки Харизмы, направленные на Гуманоидов с показателем опасности 1 или ниже. Те, на кого воздействует эффект парфюма, не понимают, что подверглись воздействию магии.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/414-perfume-of-bewitching/', 'Xanathar''s Guide to Everything'),
      ('pipe-of-smoke-monsters', 'Трубка дымных чудовищ', 'Куря эту трубку, вы можете действием выдохнуть облако дыма, которое принимает форму одного существа, например, дракона, фламфа или лягемота. Эта форма должна быть достаточно маленькой, чтобы уместиться в 1-футовый куб, и теряет очертания спустя несколько секунд, превращаясь в обычное облако дыма.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/434-pipe-of-smoke-monsters/', 'Xanathar''s Guide to Everything'),
      ('pole-of-angling', 'Шест рыболовства', 'Держа этот 10-футовый шест, вы можете произнести командное слово и трансформировать его в рыболовную удочку с крючком, леской и поплавком. Повторное произнесение слова снова превращает его в 10-футовый шест.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/436-pole-of-angling/', 'Xanathar''s Guide to Everything'),
      ('pole-of-collapsing', 'Складной шест', 'Держа этот 10-футовый шест, вы можете действием произнести командное слово и сложить шест в 1-футовый жезл для удобства хранения. Вес шеста не меняется. Вы можете действием произнести другое командное слово и заставить жезл снова превратиться в шест, однако шест удлинится только настолько, насколько позволяет окружающее пространство.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/427-pole-of-collapsing/', 'Xanathar''s Guide to Everything'),
      ('pot-of-awakening', 'Горшок пробуждения', 'Если вы посадите обычный куст в этот 10-фунтовый глиняный горшок и будете выращивать его в течение 30 дней, к концу этого времени куст магическим образом превратится в [пробуждённый куст [awakened shrub]](/bestiary/397-awakened_shrub/). При пробуждении куст ломает корнями горшок, уничтожая его. Пробуждённый куст дружественен к вам. Куст ничего не делает в отсутствие команд от вас.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/395-pot-of-awakening/', 'Xanathar''s Guide to Everything'),
      ('rope-of-mending', 'Срастающаяся верёвка', 'Вы можете разрезать этот 50-футовый моток верёвки на любое количество частей, а затем действием сказать командное слово и заставить их соединиться обратно. Части должны соприкасаться друг с другом и не должны использоваться в данный момент. Срастающаяся верёвка навсегда укорачивается если её часть потеряна или уничтожена.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/429-rope-of-mending/', 'Xanathar''s Guide to Everything'),
      ('ruby-of-the-war-mage', 'Рубин боевого мага', 'Испещрённый магическими рунами, этот рубин диаметром 1 дюйм (2,5 см) позволяет использовать простое или воинское оружие в качестве заклинательной фокусировки. Чтобы это сделать, вы должны прикрепить рубин к оружию, прижимая его к оружию не менее 10 минут. После этого удалить рубин можно будет только действием или уничтожив оружие. Даже [преграда магии [antimagic field]](/spells/263-antimagic_field/) не заставит его отсоединиться. Рубин падает с оружия, если ваша настройка на него оканчивается.', 'wondrous', 'common', null, null, null, true, 'https://dnd.su/items/422-ruby-of-the-war-mage/', 'Xanathar''s Guide to Everything'),
      ('shield-of-expression', 'Щит экспрессии', 'Передняя сторона щита имеет форму лица. Когда вы носите щит, вы можете бонусным действием поменять выражение лица на нём.', 'armor', 'common', null, null, 'shield', false, 'https://dnd.su/items/440-shield-of-expression/', 'Xanathar''s Guide to Everything'),
      ('smoldering-armor', 'Дымящий доспех', 'Когда этот доспех надет, он источает клубы не имеющего запаха безвредного дыма.', 'armor', 'common', null, null, 'body', false, 'https://dnd.su/items/398-smoldering-armor/', 'Xanathar''s Guide to Everything'),
      ('staff-of-adornment', 'Посох украшения', 'Если вы размещаете объект, весящий не более 1 фунта (такой как осколок кристалла, яйцо или камень) выше навершия посоха, пока держите его, объект поднимается на дюйм от навершия посоха и остаётся там до тех пор, пока не будет перемещён или пока посох находится у вас. Посох может одновременно удерживать до трёх таких объектов плавающими над его навершием. Пока вы держите посох, вы можете заставить один или несколько объектов медленно вращаться вокруг своей оси или вокруг друг друга.', 'magic-item', 'common', null, null, null, false, 'https://dnd.su/items/418-staff-of-adornment/', 'Xanathar''s Guide to Everything'),
      ('staff-of-birdcalls', 'Посох птичьего щебета', 'Этот деревянный посох украшен резьбой в виде птиц. У него 10 зарядов. Держа посох, вы можете действием потратить один заряд и создать на расстоянии до 60 футов один из следующих звуков: чириканье вьюрка, карканье ворона, кряканье утки, кудахтанье курицы, гогот гуся, клич гагары, кулдыканье индюка, плач чайки, уханье совы или крик орла. Посох ежедневно восстанавливает 1к6 +4 заряда на рассвете. Если вы потратили последний заряд, бросьте к20. Если выпадет 1, посох взрывается безвредным облаком птичьих перьев и пропадает навсегда.', 'magic-item', 'common', null, null, null, false, 'https://dnd.su/items/417-staff-of-birdcalls/', 'Xanathar''s Guide to Everything'),
      ('staff-of-flowers', 'Посох цветов', 'У этого деревянного посоха 10 зарядов. Держа посох, вы можете действием потратить один заряд. Пробуждённый силой посоха цветок вырастет на почве или грязи в пределах 5 футов от вас или на самом посохе. Если вы не выбрали тип цветка, посох создаёт маргаритку с лёгким запахом. Цветок безвредный и немагический. Он растёт и увядает как обычный цветок.

Посох ежедневно восстанавливает 1к6 +4 заряда на рассвете. Если вы потратили последний заряд, бросьте к20. Если выпадет 1, посох превращается в лепестки цветов и пропадает навсегда.', 'magic-item', 'common', null, null, null, false, 'https://dnd.su/items/419-staff-of-flowers/', 'Xanathar''s Guide to Everything'),
      ('talking-doll', 'Говорящая кукла', 'Пока кукла находится в пределах 5 футов от вас, вы можете во время короткого отдыха сказать ей до шести фраз, ни одна из которых не может быть длиннее шести слов, и установить условия, при которых кукла будет говорить каждую фразу. Каким бы ни было условие, оно должно совершиться в пределах 5 футов от куклы, чтобы она заговорила. Например, когда кто-то поднимет куклу, она может сказать: «Я хочу конфетку». Фразы куклы теряются, когда ваша настройка на неё заканчивается.', 'wondrous', 'common', null, null, null, true, 'https://dnd.su/items/394-talking-doll/', 'Xanathar''s Guide to Everything'),
      ('tankard-of-sobriety', 'Кружка трезвости', 'На одной стороне этой кружки изображено суровое лицо. Вы можете пить из этой кружки эль, вино или любой другой немагический алкоголь и не пьянеть. Кружка не оказывает никакого эффекта на магический алкоголь и вредные вещества, такие как яд.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/405-tankard-of-sobriety/', 'Xanathar''s Guide to Everything'),
      ('unbreakable-arrow', 'Несломимая стрела', 'Эта стрела не может быть сломана, кроме как в области действия [преграды магии [antimagic field]](/spells/263-antimagic_field/).', 'weapon', 'common', null, null, '1-handed', false, 'https://dnd.su/items/407-unbreakable-arrow/', 'Xanathar''s Guide to Everything'),
      ('veterans-cane', 'Трость ветерана', 'Когда вы сжимаете эту трость и бонусным действием произносите командное слово, трость превращается в обычный длинный меч и перестаёт быть магической.', 'wondrous', 'common', null, null, null, false, 'https://dnd.su/items/433-veterans-cane/', 'Xanathar''s Guide to Everything'),
      ('walloping-ammunition', 'Опрокидывающий боеприпас', 'Этот боеприпас содержит в себе скрытый сильный удар. Существо, в которое попал такой боеприпас, должно преуспеть в спасброске Силы Сл 10, иначе будет сбито с ног.', 'weapon', 'common', null, null, '1-handed', false, 'https://dnd.su/items/408-walloping-ammunition/', 'Xanathar''s Guide to Everything'),
      ('wand-of-conducting', 'Дирижёрская палочка', 'У этой волшебной палочки 3 заряда. Если вы её держите, вы можете действием потратить 1 заряд, чтобы создать оркестровую музыку, размахивая ею. Музыку слышно на расстоянии 60 футов, и она заканчивается, когда вы перестанете размахивать палочкой.

Палочка ежедневно восстанавливает все заряды на рассвете. Если вы потратили последний заряд, бросьте к20. Если выпадет 1, играет грустный тромбон, а палочка рассыпается в пыль и уничтожается.', 'magic-item', 'common', null, null, null, false, 'https://dnd.su/items/396-wand-of-conducting/', 'Xanathar''s Guide to Everything'),
      ('wand-of-pyrotechnics', 'Палочка пиротехники', 'У этой волшебной палочки 7 зарядов. Если вы её держите, вы можете действием потратить 1 заряд, чтобы создать безвредную разноцветную вспышку света в точке в пределах 60 футов. Эта вспышка сопровождается потрескивающим шумом, слышимым на расстоянии 300 футов. Свет такой же яркий, как пламя факела, но длится всего секунду.

Палочка ежедневно восстанавливает 1к6+1 заряд на рассвете. Если вы потратили последний заряд, бросьте к20. Если выпадет 1, палочка взрывается безвредным пиротехническим всполохом и уничтожается.', 'magic-item', 'common', null, null, null, false, 'https://dnd.su/items/411-wand-of-pyrotechnics/', 'Xanathar''s Guide to Everything'),
      ('wand-of-scowls', 'Палочка хмурых взглядов', 'У этой волшебной палочки 3 заряда. Если вы её держите, вы можете действием потратить 1 заряд и выбрать в качестве цели гуманоида, которого видите в пределах 30 футов. Цель должна преуспеть в спасброске Харизмы Сл 10, иначе она будет хмуриться 1 минуту.

Палочка восстанавливает все заряды на рассвете. Если вы потратили последний заряд, бросьте к20. Если выпадет 1, палочка превращается в [палочку улыбок [Wand of Smiles]](/items/412-wand_of_smiles/).', 'magic-item', 'common', null, null, null, false, 'https://dnd.su/items/413-wand-of-scowls/', 'Xanathar''s Guide to Everything'),
      ('wand-of-smiles', 'Палочка улыбок', 'У этой волшебной палочки 3 заряда. Если вы её держите, вы можете действием потратить 1 заряд и выбрать в качестве цели гуманоида, которого видите в пределах 30 футов. Цель должна преуспеть в спасброске Харизмы Сл 10, иначе она будет улыбаться 1 минуту. Палочка восстанавливает все заряды на рассвете. Если вы потратили последний заряд, бросьте к20. Если выпадет 1, палочка превращается в [палочку хмурых взглядов [Wand of Scowls]](/items/413-wand_of_scowls/).', 'magic-item', 'common', null, null, null, false, 'https://dnd.su/items/412-wand-of-smiles/', 'Xanathar''s Guide to Everything')
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text,
        requires_attunement::boolean,
        dndsu_url::text,
        source_detail::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru,
          'dndsu_url', s.dndsu_url,
          'source_detail', s.source_detail
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, requires_attunement,
      source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, s.requires_attunement,
      'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su items (Xanathar''s Guide to Everything)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- Phase 2 backfill (transactions.item_node_id = N) is intentionally
-- omitted for dnd.su entries: the canonical Russian title is shared
-- across many similar items and would mis-link prior transactions.
-- DMs do per-item linking on demand from the catalog UI.

commit;
