-- Migration 141 — dnd.su spells seed: Guildmasters' Guide to Ravnica.
-- Spec-059 этап 1. Auto-generated by scripts/spells-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/spells-dndsu-codegen.ts --emit-migrations
--
-- Идемпотентность:
--   * NOT EXISTS guard на (campaign_id, node_type spell, fields->>'slug')
--     — повторный прогон не плодит дублей и не перетирает правки ДМ.
-- Тело редакции 2014 -> nodes.content; тело 2024 -> fields.content_2024
-- (nullable, переключатель редакции показывается только при наличии).
-- node_type 'spell' создан миграцией 130; здесь только вставка строк.
--
-- NB: notify pgrst 'reload schema' здесь НЕ нужен — это чистый insert строк,
-- а не DDL: схема эмбедов PostgREST не меняется (в отличие от смены колонок).

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'spell'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=spell, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      slug, title_ru, level, school, casting_time, range_, components,
      duration, concentration, ritual, classes, source, content, content_2024
    ) as (values
      ('encode-thoughts', 'Кодировка мыслей', 0, 'очарование', '1 действие', 'На себя', 'С', 'Вплоть до 8 часов', false, false, '', 'Guildmasters'' Guide to Ravnica', '## Кодировка мыслей [Encode thoughts]GGR

  * Заговор, очарование
  * **Время накладывания:** 1 действие
  * **Дистанция:** На себя
  * **Компоненты:** С
  * **Длительность:** Вплоть до 8 часов
  * Прикладывая палец к своей голове, вы извлекаете воспоминание, идею или сообщение из своего разума и трансформируете её в осязаемую ленту светящейся энергии — ленту мысли. Она существует в течение всей длительности заклинания или пока вы не наложите это заклинание снова. Лента мысли появляется в свободном пространстве в пределах 5 футов от вас как Крошечный невесомый полутвёрдый предмет, который можно держать и нести как ленту. В остальном она неподвижна.

Если вы накладываете это заклинание, пока концентрируетесь на заклинании или умении, позволяющем читать мысли других существ или манипулировать ими (например, [обнаружение мыслей [detect thoughts]](/spells/196-detect_thoughts/) или [изменение памяти [modify memory]](/spells/119-modify_memory/)), вы можете трансформировать в ленту мысли читаемые вами мысли или воспоминания.

Если вы накладываете это заклинание, пока держите ленту мысли, вы мгновенно получаете ту информацию, что содержит лента (накладывание заклинания [обнаружение мыслей [detect thoughts]](/spells/196-detect_thoughts/) на ленту имеет тот же эффект).

Это заклинание доступно только Оперативникам Димиров, имеющим умение «Использование заклинаний» или «Магия договора»

**— Господин Финик**', null)
    ),
    typed_seed as (
      select
        slug::text,
        title_ru::text,
        level::int,
        school::text,
        casting_time::text,
        range_::text,
        components::text,
        duration::text,
        concentration::boolean,
        ritual::boolean,
        classes::text,
        source::text,
        content::text,
        content_2024::text
      from seed
    )
    insert into nodes (campaign_id, type_id, title, content, fields)
    select
      c_rec.id,
      type_id_v,
      s.title_ru,
      s.content,
      jsonb_build_object(
        'level', s.level,
        'school', s.school,
        'casting_time', s.casting_time,
        'range', s.range_,
        'components', s.components,
        'duration', s.duration,
        'concentration', s.concentration,
        'ritual', s.ritual,
        'classes', s.classes,
        'source', s.source,
        'slug', s.slug,
        'content_2024', coalesce(s.content_2024, '')
      )
    from typed_seed s
    where not exists (
      select 1 from nodes n
      where n.campaign_id = c_rec.id
        and n.type_id = type_id_v
        and n.fields->>'slug' = s.slug
    );

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su spells (Guildmasters'' Guide to Ravnica)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

commit;

-- ─────────────────────────── Verify ───────────────────────────
-- Ни одна засеянная spell-нода не должна иметь пустой slug.
select case
  when not exists (
    select 1 from nodes n
    join node_types t on t.id = n.type_id
    where t.slug = 'spell' and coalesce(n.fields->>'slug', '') = ''
  )
  then '✅ миграция 141 (Guildmasters'' Guide to Ravnica): spell-ноды со slug'
  else '❌ есть spell-ноды с пустым slug'
end as result;
