-- Migration 144 — dnd.su spells seed: Strixhaven: A Curriculum of Chaos.
-- Spec-059 этап 1. Auto-generated by scripts/spells-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/spells-dndsu-codegen.ts --emit-migrations
--
-- Идемпотентность:
--   * NOT EXISTS guard на (campaign_id, node_type spell, fields->>'slug')
--     — повторный прогон не плодит дублей и не перетирает правки ДМ.
-- Тело редакции 2014 -> nodes.content; тело 2024 -> fields.content_2024
-- (nullable, переключатель редакции показывается только при наличии).
-- node_type 'spell' создан миграцией 130; здесь только вставка строк.
--
-- NB: notify pgrst 'reload schema' здесь НЕ нужен — это чистый insert строк,
-- а не DDL: схема эмбедов PostgREST не меняется (в отличие от смены колонок).

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'spell'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=spell, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      slug, title_ru, level, school, casting_time, range_, components,
      duration, concentration, ritual, classes, source, content, content_2024
    ) as (values
      ('silvery-barbs', 'Искусная острота', 1, 'очарование', '1 реакция, совершаемая вами, когда видимое вами в пределах 60 футов от вас существо преуспевает в броске атаки, проверке характеристики или спасброске', '60 футов', 'В', 'Мгновенная', false, false, 'бард, волшебник, чародей', 'Strixhaven: A Curriculum of Chaos', '## Искусная острота [Silvery barbs]SCC

  * 1 уровень, очарование
  * **Время накладывания:** 1 реакция, совершаемая вами, когда видимое вами в пределах 60 футов от вас существо преуспевает в броске атаки, проверке характеристики или спасброске
  * **Дистанция:** 60 футов
  * **Компоненты:** В
  * **Длительность:** Мгновенная
  * **Классы:** бард, волшебник, чародей
  * Вы магическим образом отвлекаете спровоцировавшее реакцию существо и превращаете его секундное замешательство в ободрение другого существа. Спровоцировавшее вас существо должно повторно совершить бросок к20 и использовать меньшее значение.

После этого вы можете выбрать другое существо, которое видите в пределах дистанции (вы можете выбрать себя). Выбранное существо совершит с преимуществом следующий бросок атаки, проверку характеристики или спасбросок, который оно совершит в течение 1 минуты. Существо может иметь на себе лишь одно усиление от этого заклинания за раз.', null)
    ),
    typed_seed as (
      select
        slug::text,
        title_ru::text,
        level::int,
        school::text,
        casting_time::text,
        range_::text,
        components::text,
        duration::text,
        concentration::boolean,
        ritual::boolean,
        classes::text,
        source::text,
        content::text,
        content_2024::text
      from seed
    )
    insert into nodes (campaign_id, type_id, title, content, fields)
    select
      c_rec.id,
      type_id_v,
      s.title_ru,
      s.content,
      jsonb_build_object(
        'level', s.level,
        'school', s.school,
        'casting_time', s.casting_time,
        'range', s.range_,
        'components', s.components,
        'duration', s.duration,
        'concentration', s.concentration,
        'ritual', s.ritual,
        'classes', s.classes,
        'source', s.source,
        'slug', s.slug,
        'content_2024', coalesce(s.content_2024, '')
      )
    from typed_seed s
    where not exists (
      select 1 from nodes n
      where n.campaign_id = c_rec.id
        and n.type_id = type_id_v
        and n.fields->>'slug' = s.slug
    );

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su spells (Strixhaven: A Curriculum of Chaos)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

commit;

-- ─────────────────────────── Verify ───────────────────────────
-- Ни одна засеянная spell-нода не должна иметь пустой slug.
select case
  when not exists (
    select 1 from nodes n
    join node_types t on t.id = n.type_id
    where t.slug = 'spell' and coalesce(n.fields->>'slug', '') = ''
  )
  then '✅ миграция 144 (Strixhaven: A Curriculum of Chaos): spell-ноды со slug'
  else '❌ есть spell-ноды с пустым slug'
end as result;
