-- Migration 145 — dnd.su spells seed: Sword Coast Adventurer's Guide.
-- Spec-059 этап 1. Auto-generated by scripts/spells-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/spells-dndsu-codegen.ts --emit-migrations
--
-- Идемпотентность:
--   * NOT EXISTS guard на (campaign_id, node_type spell, fields->>'slug')
--     — повторный прогон не плодит дублей и не перетирает правки ДМ.
-- Тело редакции 2014 -> nodes.content; тело 2024 -> fields.content_2024
-- (nullable, переключатель редакции показывается только при наличии).
-- node_type 'spell' создан миграцией 130; здесь только вставка строк.
--
-- NB: notify pgrst 'reload schema' здесь НЕ нужен — это чистый insert строк,
-- а не DDL: схема эмбедов PostgREST не меняется (в отличие от смены колонок).

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'spell'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=spell, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      slug, title_ru, level, school, casting_time, range_, components,
      duration, concentration, ritual, classes, source, content, content_2024
    ) as (values
      ('booming-blade', 'Громовой клинок', 0, 'воплощение', '1 действие', 'На себя (5-футовый радиус)', 'С, М (рукопашное оружие стоимостью не менее 1 см)', '1 раунд', false, false, 'волшебник, изобретатель, колдун, чародей', 'Sword Coast Adventurer''s Guide', '## Громовой клинок [Booming blade]SCAG TCE

  * Заговор, воплощение
  * **Время накладывания:** 1 действие
  * **Дистанция:** На себя (5-футовый радиус)
  * **Компоненты:** С, М (рукопашное оружие стоимостью не менее 1 см)
  * **Длительность:** 1 раунд
  * **Классы:** волшебник, изобретатель, колдун, чародей
  * Вы взмахиваете оружием, выбранным в качестве материального компонента, и совершаете им рукопашную атаку оружием против одного существа в пределах 5 футов от вас. При попадании цель подвергается обычному эффекту от атаки этим оружием и покрывается бушующей энергией до начала вашего следующего хода. Если цель добровольно перемещается на 5 футов или более до окончания действия заклинания, она получает 1к8 урона звуком, и действие заклинания заканчивается.

Урон этого заклинания увеличивается, когда вы достигаете определённых уровней. На 5-м уровне рукопашная атака наносит дополнительно 1к8 урона звуком при попадании, а урон, получаемый при перемещении, увеличивается до 2к8. Оба броска урона снова увеличиваются на 1к8 на 11-м уровне (2к8 и 3к8) и на 17-м уровне (3к8 и 4к8).', null),
      ('green-flame-blade', 'Клинок зелёного пламени', 0, 'воплощение', '1 действие', 'На себя (5-футовый радиус)', 'С, М (рукопашное оружие стоимостью не менее 1 см)', 'Мгновенная', false, false, 'волшебник, изобретатель, колдун, чародей', 'Sword Coast Adventurer''s Guide', '## Клинок зелёного пламени [Green-flame blade]SCAG TCE

  * Заговор, воплощение
  * **Время накладывания:** 1 действие
  * **Дистанция:** На себя (5-футовый радиус)
  * **Компоненты:** С, М (рукопашное оружие стоимостью не менее 1 см)
  * **Длительность:** Мгновенная
  * **Классы:** волшебник, изобретатель, колдун, чародей
  * Вы взмахиваете оружием, выбранным в качестве материального компонента, и совершаете им рукопашную атаку оружием против одного существа в пределах 5 футов от вас. При попадании цель подвергается обычному эффекту атаки этим оружием, и вы можете заставить зелёный огонь перекинуться от цели к другому существу по вашему выбору, которое вы можете видеть в пределах 5 футов от цели. Второе существо получает урон огнём, равный вашему модификатору базовой характеристики.

Урон этого заклинания увеличивается, когда вы достигаете определенных уровней. На 5-м уровне рукопашная атака наносит дополнительно 1к8 урона огнём, а урон, получаемый вторым существом, увеличивается до 1к8 + ваш модификатор базовой характеристики. Оба этих урона увеличиваются на 1к8 на 11-м уровне (2к8 и 2к8) и 17-м уровне (3к8 и 3к8).', null),
      ('lightning-lure', 'Лассо молнии', 0, 'воплощение', '1 действие', 'На себя (15-футовый радиус)', 'В', 'Мгновенная', false, false, 'волшебник, изобретатель, колдун, чародей', 'Sword Coast Adventurer''s Guide', '## Лассо молнии [Lightning lure]SCAG TCE

  * Заговор, воплощение
  * **Время накладывания:** 1 действие
  * **Дистанция:** На себя (15-футовый радиус)
  * **Компоненты:** В
  * **Длительность:** Мгновенная
  * **Классы:** волшебник, изобретатель, колдун, чародей
  * Вы создаёте хлыст из молний, поражающий одно существо по вашему выбору, которое вы можете видеть в пределах 15 футов от вас. Цель должна преуспеть в спасброске Силы, иначе будет притянута на 10 футов по прямой к вам, после чего получит 1к8 урона электричеством, если окажется в пределах 5 футов от вас.

Урон этого заклинания увеличивается на 1к8, когда вы достигаете 5-го уровня (2к8), 11-го уровня (3к8) и 17-го уровня (4к8).', null),
      ('sword-burst', 'Вспышка мечей', 0, 'вызов', '1 действие', 'На себя (5-футовый радиус)', 'В', 'Мгновенная', false, false, 'волшебник, изобретатель, колдун, чародей', 'Sword Coast Adventurer''s Guide', '## Вспышка мечей [Sword burst]SCAG TCE

  * Заговор, вызов
  * **Время накладывания:** 1 действие
  * **Дистанция:** На себя (5-футовый радиус)
  * **Компоненты:** В
  * **Длительность:** Мгновенная
  * **Классы:** волшебник, изобретатель, колдун, чародей
  * Вы на мгновение создаёте круг из вращающихся вокруг вас призрачных лезвий. Все остальные существа в пределах 5 футов от вас должны преуспеть в спасброске Ловкости, иначе получат 1к6 урона силовым полем.

Урон этого заклинания увеличивается на 1к6, когда вы достигаете 5-го уровня (2к6), 11-го уровня (3к6) и 17-го уровня (4к6).', null)
    ),
    typed_seed as (
      select
        slug::text,
        title_ru::text,
        level::int,
        school::text,
        casting_time::text,
        range_::text,
        components::text,
        duration::text,
        concentration::boolean,
        ritual::boolean,
        classes::text,
        source::text,
        content::text,
        content_2024::text
      from seed
    )
    insert into nodes (campaign_id, type_id, title, content, fields)
    select
      c_rec.id,
      type_id_v,
      s.title_ru,
      s.content,
      jsonb_build_object(
        'level', s.level,
        'school', s.school,
        'casting_time', s.casting_time,
        'range', s.range_,
        'components', s.components,
        'duration', s.duration,
        'concentration', s.concentration,
        'ritual', s.ritual,
        'classes', s.classes,
        'source', s.source,
        'slug', s.slug,
        'content_2024', coalesce(s.content_2024, '')
      )
    from typed_seed s
    where not exists (
      select 1 from nodes n
      where n.campaign_id = c_rec.id
        and n.type_id = type_id_v
        and n.fields->>'slug' = s.slug
    );

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su spells (Sword Coast Adventurer''s Guide)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

commit;

-- ─────────────────────────── Verify ───────────────────────────
-- Ни одна засеянная spell-нода не должна иметь пустой slug.
select case
  when not exists (
    select 1 from nodes n
    join node_types t on t.id = n.type_id
    where t.slug = 'spell' and coalesce(n.fields->>'slug', '') = ''
  )
  then '✅ миграция 145 (Sword Coast Adventurer''s Guide): spell-ноды со slug'
  else '❌ есть spell-ноды с пустым slug'
end as result;
