-- Migration 146 — dnd.su spells seed: Tasha's Cauldron of Everything.
-- Spec-059 этап 1. Auto-generated by scripts/spells-dndsu-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/spells-dndsu-codegen.ts --emit-migrations
--
-- Идемпотентность:
--   * NOT EXISTS guard на (campaign_id, node_type spell, fields->>'slug')
--     — повторный прогон не плодит дублей и не перетирает правки ДМ.
-- Тело редакции 2014 -> nodes.content; тело 2024 -> fields.content_2024
-- (nullable, переключатель редакции показывается только при наличии).
-- node_type 'spell' создан миграцией 130; здесь только вставка строк.
--
-- NB: notify pgrst 'reload schema' здесь НЕ нужен — это чистый insert строк,
-- а не DDL: схема эмбедов PostgREST не меняется (в отличие от смены колонок).

begin;

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'spell'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=spell, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      slug, title_ru, level, school, casting_time, range_, components,
      duration, concentration, ritual, classes, source, content, content_2024
    ) as (values
      ('mind-sliver', 'Расщепление разума', 0, 'очарование', '1 действие', '60 футов', 'В', '1 раунд', false, false, 'волшебник, колдун, чародей', 'Tasha''s Cauldron of Everything', '## Расщепление разума [Mind Sliver]TCE PH24

  * Заговор, очарование
  * **Время накладывания:** 1 действие
  * **Дистанция:** 60 футов
  * **Компоненты:** В
  * **Длительность:** 1 раунд
  * **Классы:** волшебник, колдун, чародей
  * **Подклассы:** аберрантный разум (чародей)
  * Вы отправляете дезориентирующий луч психической энергии в разум одного существа, которое видите в пределах дистанции. Цель должна преуспеть в спасброске Интеллекта, иначе получит 1к6 урона психической энергией и вычтет 1к4 из следующего спасброска, совершаемого ею до конца вашего следующего хода.

Урон этого заклинания увеличивается на 1к6, когда вы достигаете следующих уровней: 5-го уровня (2к6), 11-го уровня (3к6) и 17-го уровня (4к6).', '##  Расщепление разума [Mind Sliver]

  * Заговор, Очарование
  * **Время сотворения:** Действие
  * **Дистанция:** 60 футов
  * **Компоненты:** В
  * **Длительность:** 1 раунд
  * **Классы:** Волшебник, Колдун, Чародей
  * **Подклассы:** Аберрантное чародейство (Чародей)
  * Вы пытаетесь расщепить разум существа, видимого вами в пределах дистанции. Цель должна преуспеть в спасброске Интеллекта, иначе получит 1к6 Психического урона и вычтет 1к4 из результата своего следующего спасброска, если совершит его до конца вашего следующего хода.

Усиление заговора.

Урон увеличивается на 1к6, когда вы достигаете 5-го (2к6), 11-го (3к6) и 17-го (4к6) уровней.'),
      ('tashas-caustic-brew', 'Едкое варево Таши', 1, 'воплощение', '1 действие', 'На себя (30-футовая линия)', 'В, С, М (немного тухлой пищи)', 'Концентрация, вплоть до 1 минуты', true, false, 'волшебник, изобретатель, чародей', 'Tasha''s Cauldron of Everything', '## Едкое варево Таши [Tasha''s Caustic Brew]TCE

  * 1 уровень, воплощение
  * **Время накладывания:** 1 действие
  * **Дистанция:** На себя (30-футовая линия)
  * **Компоненты:** В, С, М (немного тухлой пищи)
  * **Длительность:** Концентрация, вплоть до 1 минуты
  * **Классы:** волшебник, изобретатель, чародей
  * Вы испускаете струю кислоты вдоль линии длиной 30 футов и шириной 5 футов в выбранном вами направлении. Каждое существо, находящееся на этой линии должно преуспеть в спасброске Ловкости, иначе станет покрыто кислотой на время действия заклинания или до тех пор, пока кто-то действием не соскребёт или смоет кислоту с себя или другого существа. Существо, покрытое кислотой, получает 2к4 урона кислотой в начале каждого своего хода.

**_На больших уровнях._** Когда вы накладываете это заклинание, используя ячейку 2-го уровня или выше, урон увеличивается на 2к4 за каждый уровень ячейки выше первого.', null)
    ),
    typed_seed as (
      select
        slug::text,
        title_ru::text,
        level::int,
        school::text,
        casting_time::text,
        range_::text,
        components::text,
        duration::text,
        concentration::boolean,
        ritual::boolean,
        classes::text,
        source::text,
        content::text,
        content_2024::text
      from seed
    )
    insert into nodes (campaign_id, type_id, title, content, fields)
    select
      c_rec.id,
      type_id_v,
      s.title_ru,
      s.content,
      jsonb_build_object(
        'level', s.level,
        'school', s.school,
        'casting_time', s.casting_time,
        'range', s.range_,
        'components', s.components,
        'duration', s.duration,
        'concentration', s.concentration,
        'ritual', s.ritual,
        'classes', s.classes,
        'source', s.source,
        'slug', s.slug,
        'content_2024', coalesce(s.content_2024, '')
      )
    from typed_seed s
    where not exists (
      select 1 from nodes n
      where n.campaign_id = c_rec.id
        and n.type_id = type_id_v
        and n.fields->>'slug' = s.slug
    );

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new dnd.su spells (Tasha''s Cauldron of Everything)',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

commit;

-- ─────────────────────────── Verify ───────────────────────────
-- Ни одна засеянная spell-нода не должна иметь пустой slug.
select case
  when not exists (
    select 1 from nodes n
    join node_types t on t.id = n.type_id
    where t.slug = 'spell' and coalesce(n.fields->>'slug', '') = ''
  )
  then '✅ миграция 146 (Tasha''s Cauldron of Everything): spell-ноды со slug'
  else '❌ есть spell-ноды с пустым slug'
end as result;
