/**
 * scripts/items-srd-codegen.ts — spec-015 (T034).
 *
 * Reads `lib/seeds/items-srd.ts` and emits a self-contained SQL block
 * suitable for inclusion in a Postgres migration. The output goes to
 * stdout; the maintainer pipes it into the migration file:
 *
 *   npx tsx scripts/items-srd-codegen.ts > supabase/migrations/044_srd_items_seed.sql
 *
 * Re-running with the same seed input produces byte-identical output
 * (modulo TypeScript number formatting), so the migration stays in
 * sync with the seed data when entries are added or revised.
 *
 * Output structure (matches T035):
 *   Phase 1 — per-campaign INSERT of nodes + item_attributes via a
 *             single CTE; ON-CONFLICT-style idempotency through a
 *             NOT EXISTS guard on `(campaign_id, fields->>'srd_slug')`.
 *   Phase 2 — per-campaign UPDATE of transactions.item_node_id
 *             where `LOWER(TRIM(item_name)) = LOWER(TRIM(title))`
 *             OR `LOWER(TRIM(item_name)) = LOWER(srd_slug)`.
 *   RAISE NOTICE per campaign with insert + backfill counts (FR-029).
 */

import { ITEMS_SRD_SEED, type ItemSeedEntry } from '../lib/seeds/items-srd'

function escSqlString(s: string): string {
  return s.replace(/'/g, "''")
}

function num(v: number | null): string {
  return v === null ? 'null' : String(v)
}

function strLit(v: string | null): string {
  return v === null ? 'null' : `'${escSqlString(v)}'`
}

function tupleFor(e: ItemSeedEntry): string {
  return [
    strLit(e.srdSlug),
    strLit(e.titleRu),
    strLit(e.descriptionRu || null),
    strLit(e.category),
    strLit(e.rarity),
    num(e.priceGp),
    num(e.weightLb),
    strLit(e.slot),
  ].join(', ')
}

function valuesBlock(): string {
  // Cast the first row's columns so Postgres can infer types when
  // some columns are entirely NULL (rarity, slot for mundane items).
  const lines = ITEMS_SRD_SEED.map((e, i) => {
    const cast =
      i === 0
        ? `(${tupleFor(e)})::record`
        : `(${tupleFor(e)})`
    return `      ${cast}`
  })
  return lines.join(',\n')
}

function emitSql(): string {
  const seedRows = ITEMS_SRD_SEED.map((e) => `      (${tupleFor(e)})`).join(',\n')

  return `-- Migration 044 — SRD item seed + transactions backfill.
-- Spec-015 T035. Auto-generated by scripts/items-srd-codegen.ts —
-- DO NOT edit by hand; regenerate with:
--
--   npx tsx scripts/items-srd-codegen.ts > supabase/migrations/044_srd_items_seed.sql
--
-- Idempotency:
--   * Phase 1: NOT EXISTS guard on (campaign_id, fields->>'srd_slug')
--     — re-running adds no duplicates and never overwrites DM edits.
--   * Phase 2: only sets item_node_id where it is NULL — re-running
--     never re-points a row that's already linked.

begin;

-- ─────────────────────────── Phase 1: seed ───────────────────────────

do $$
declare
  c_rec record;
  type_id_v uuid;
  ins_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    select id into type_id_v from node_types
      where campaign_id = c_rec.id and slug = 'item'
      limit 1;

    if type_id_v is null then
      raise notice 'Campaign % (%): no node_type=item, skipping seed',
        c_rec.slug, c_rec.id;
      continue;
    end if;

    with seed(
      srd_slug, title_ru, description_ru,
      category, rarity, price_gp, weight_lb, slot
    ) as (values
${seedRows}
    ),
    typed_seed as (
      select
        srd_slug::text,
        title_ru::text,
        description_ru::text,
        category::text,
        rarity::text,
        price_gp::numeric,
        weight_lb::numeric,
        slot::text
      from seed
    ),
    inserted as (
      insert into nodes (campaign_id, type_id, title, fields)
      select
        c_rec.id,
        type_id_v,
        s.title_ru,
        jsonb_strip_nulls(jsonb_build_object(
          'srd_slug', s.srd_slug,
          'description', s.description_ru
        ))
      from typed_seed s
      where not exists (
        select 1 from nodes n
        where n.campaign_id = c_rec.id
          and n.fields->>'srd_slug' = s.srd_slug
      )
      returning id, fields->>'srd_slug' as srd_slug
    )
    insert into item_attributes (
      node_id, category_slug, rarity, price_gp, weight_lb,
      slot_slug, source_slug, availability_slug
    )
    select
      i.id, s.category, s.rarity, s.price_gp, s.weight_lb,
      s.slot, 'srd-5e', null
    from inserted i
    join typed_seed s on s.srd_slug = i.srd_slug
    on conflict (node_id) do nothing;

    get diagnostics ins_count = row_count;
    raise notice 'Campaign % (%): inserted % new SRD items',
      c_rec.slug, c_rec.id, ins_count;
  end loop;
end $$;

-- ─────────────────────────── Phase 2: backfill ───────────────────────────

do $$
declare
  c_rec record;
  bf_count int;
begin
  for c_rec in select id, slug from campaigns order by created_at loop
    update transactions tx
    set item_node_id = n.id
    from nodes n
    inner join item_attributes ia on ia.node_id = n.id
    where tx.campaign_id = c_rec.id
      and tx.kind = 'item'
      and tx.item_node_id is null
      and n.campaign_id = c_rec.id
      and ia.source_slug = 'srd-5e'
      and (
        lower(trim(tx.item_name)) = lower(trim(n.title))
        or lower(trim(coalesce(tx.item_name, ''))) = lower(coalesce(n.fields->>'srd_slug', ''))
      );

    get diagnostics bf_count = row_count;
    raise notice 'Campaign % (%): backfilled % transactions',
      c_rec.slug, c_rec.id, bf_count;
  end loop;
end $$;

commit;

-- Post-deploy verification (run manually if desired):
--
--   -- (a) seeded item count per campaign (expect ${ITEMS_SRD_SEED.length} for fresh seeding)
--   select c.slug, count(n.id)
--     from campaigns c
--     left join nodes n on n.campaign_id = c.id
--                       and n.fields->>'srd_slug' is not null
--     group by c.slug order by c.slug;
--
--   -- (b) backfilled transactions per campaign
--   select c.slug, count(tx.id)
--     from campaigns c
--     left join transactions tx on tx.campaign_id = c.id
--                               and tx.item_node_id is not null
--                               and tx.kind = 'item'
--     group by c.slug order by c.slug;
--
--   -- (c) sanity: kind/link CHECK still satisfied
--   select count(*) from transactions
--     where (kind = 'item' and item_node_id is not null and false /* should never trip */)
--        or (kind <> 'item' and item_node_id is not null);
`
}

// Suppress unused warning — kept around for future use.
void valuesBlock

console.log(emitSql())
